# German answer text translations for gen101-gen200 (same order as English answers)
DE_ANSWER_TEXTS_NEW1 = {
    "gen101": ["Chips", "Sellerie", "Aepfel", "Moehren", "Muesli", "Suppe"],
    "gen102": ["Wein", "Politik", "Kunst", "Klassische Musik", "Finanzen", "Auslaendische Kueche"],
    "gen103": ["Titanic", "The Notebook", "Bambi", "Up", "Marley & Me", "The Lion King"],
    "gen104": ["Kaffee", "Kerzen", "Vanilleextrakt", "Parfuem", "Seife", "Kakaopulver"],
    "gen105": ["Sprache nicht lernen", "Falsches Trinkgeld", "In Touristenfallen essen", "Falsche Kleidung", "Braeuche nicht respektieren", "Zu viel einpacken"],
    "gen106": ["Baer", "Nilpferd", "Koala", "Waschbaer", "Kugelfisch", "Schimpanse"],
    "gen107": ["Schluessel", "Fernbedienung", "Handy", "Brille", "Socken", "Portemonnaie"],
    "gen108": ["Arzt", "Astronaut", "Feuerwehrmann", "Sportler", "Tierarzt", "Lehrer"],
    "gen109": ["Fernsehen", "Social Media scrollen", "Snacks essen", "Putzen", "Nickerchen", "Tagtraeumen"],
    "gen110": ["Necessary", "Restaurant", "Wednesday", "Definitely", "Separate", "Receive"],
    "gen111": ["Zahnbuerste", "Ladekabel", "Unterwaesche", "Socken", "Sonnencreme", "Medikamente"],
    "gen112": ["Bonbonschale", "Spitzendeckchen", "Alte Fotos", "Plastik auf Moebeln", "Religioese Gegenstaende", "Potpourri"],
    "gen113": ["Muss frueh arbeiten", "Fuehle mich nicht gut", "Babysitter", "Haustier braucht mich", "Frueher Termin", "Verkehr"],
    "gen114": ["Musik", "Wegbeschreibung", "Temperatur", "Wo essen", "Toilettenpausen", "Fahrgeschwindigkeit"],
    "gen115": ["Golf", "Bowling", "Angeln", "Cricket", "Darts", "Badminton"],
    "gen116": ["Alter", "Beruf", "Hobbys", "Beziehungsgeschichte", "Groesse", "Was sie essen"],
    "gen117": ["Warten im Wartezimmer", "Formulare ausfuellen", "Warten im Behandlungsraum", "Versicherungskram", "Laborergebnisse", "Ueberweisung bekommen"],
    "gen118": ["Abspuelen", "Waesche", "Bad putzen", "Staubsaugen", "Wischen", "Buegeln"],
    "gen119": ["Hundegebell", "Donner", "Baby weint", "Autoalarm", "Sirenen", "Knarren"],
    "gen120": ["Knoepfe druecken", "Hilfe rufen", "Panik", "Handy checken", "Mit anderen reden", "Beten"],
    "gen121": ["Sherlock Holmes", "Scooby-Doo", "Batman", "Nancy Drew", "Inspector Clouseau", "Columbo"],
    "gen122": ["Zulassungsstelle", "Freizeitpark-Fahrgeschaefte", "Flughafen-Sicherheit", "Cafe", "Supermarktkasse", "Oeffentliche Toilette"],
    "gen123": ["Batterien", "Gummibaender", "Kugelschreiber", "Klebeband", "Lieferservice-Menues", "Alte Schluessel"],
    "gen124": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "Twinkle Twinkle Little Star", "ABC-Lied"],
    "gen125": ["Sport treiben", "Gesuender essen", "Geld sparen", "Mehr lesen", "Eine Sprache lernen", "Frueh aufstehen"],
    "gen126": ["Brokkoli", "Rosenkohl", "Spinat", "Spargel", "Erbsen", "Blumenkohl"],
    "gen127": ["Handy", "Schluessel", "Portemonnaie", "Haare", "Herd", "Tuer abschliessen"],
    "gen128": ["Eiffelturm", "Freiheitsstatue", "Schiefer Turm von Pisa", "Big Ben", "Chinesische Mauer", "Kolosseum"],
    "gen129": ["Mitsingen", "Lauter drehen", "Tanzen", "Das ist mein Lied sagen", "Luftgitarre", "Augen schliessen"],
    "gen130": ["123456", "Password", "Ihr Geburtstag", "Tiername", "Qwerty", "abc123"],
    "gen131": ["Eichhoernchen", "Vogel", "Kaninchen", "Reh", "Waschbaer", "Opossum"],
    "gen132": ["Kopfhoerer", "Weihnachtsbeleuchtung", "Haare", "Angelschnur", "Halsketten", "Verlaengerungskabel"],
    "gen133": ["Die Rechnung", "Mehr Brot", "Einen anderen Tisch", "Aenderungen am Gericht", "Restebox", "Den Geschaeftsfuehrer"],
    "gen134": ["Thanksgiving", "Weihnachten", "Ostern", "4. Juli", "Hanukkah", "Super Bowl Sunday"],
    "gen135": ["Wasser", "Essen", "Parken", "Souvenirs", "WLAN", "Zeitschriften"],
    "gen136": ["Krank fuehlen", "Zu muede", "Arbeit", "Schlechtes Wetter", "Familiennotfall", "Keine Lust"],
    "gen137": ["Briefmarken", "Muenzen", "Actionfiguren", "Sammelkarten", "Schallplatten", "Muscheln"],
    "gen138": ["Bibliothek", "Kirche", "Kino", "Krankenhaus", "Babyzimmer", "Beerdigung"],
    "gen139": ["Cornhole", "Hufeisen werfen", "Volleyball", "Frisbee", "Kartenspiele", "Badminton"],
    "gen140": ["Handy benutzen", "Muenzen aufheben", "Schuhe binden", "Hemd zuknuepfen", "Schreiben", "Glas oeffnen"],
    "gen141": ["Hogwarts", "Narnia", "Wakanda", "Middle-earth", "Neverland", "Willy Wonkas Fabrik"],
    "gen142": ["Suessigkeiten", "Limo", "Chips", "Sandwiches", "Fast Food", "Flachmann"],
    "gen143": ["Auto", "Handy", "Toilette", "Klimaanlage", "Waschmaschine", "Internet"],
    "gen144": ["Zitrone", "Limette", "Orange", "Erdbeere", "Ananas", "Kirsche"],
    "gen145": ["Aufs Handy schauen", "Reden", "Brot essen", "Trinken", "Leute beobachten", "Speisekarte nochmal lesen"],
    "gen146": ["Friends", "The Office", "Breaking Bad", "Stranger Things", "Game of Thrones", "Grey's Anatomy"],
    "gen147": ["Apfel", "Zu korrigierende Arbeiten", "Kaffeetasse", "Stifte", "Hefter", "Namensschild"],
    "gen148": ["Blauschimmelkaese", "Durian", "Fisch", "Gekochte Eier", "Kimchi", "Rosenkohl"],
    "gen149": ["Essen", "Social Media scrollen", "Spazieren gehen", "Nickerchen", "Besorgungen machen", "Tratschen"],
    "gen150": ["Monopoly", "Risk", "Scrabble", "Uno", "Sorry!", "Trivial Pursuit"],
    "gen151": ["Wasserglas", "Handy", "Kugelschreiber", "Vase", "Schluessel", "Fernbedienung"],
    "gen152": ["Baby weint", "Alarm", "Kreide an der Tafel", "Schnarchen", "Hundegebell", "Handy klingelt"],
    "gen153": ["Aufs Handy schauen", "Miteinander reden", "Trinken", "Brot essen", "Essen anderer anschauen", "Speisekarte nochmal lesen"],
    "gen154": ["Neues Outfit", "Urlaub", "Mit Freunden", "Social Media", "Besonderer Anlass", "Langeweile"],
    "gen155": ["Toilettenpapier", "Handyakku", "Benzin", "Geld", "Heisses Wasser", "Milch"],
    "gen156": ["Pfannkuchen", "Steak", "Eier", "Sandwich", "Pasta", "Grilled Cheese"],
    "gen157": ["Toilette", "Spiegel", "Waschbecken", "Seife", "Handtuch", "Toilettenpapier"],
    "gen158": ["Die Bibel", "AGBs", "Klassische Romane", "Shakespeare", "Arbeits-E-Mails", "Nachrichtenartikel"],
    "gen159": ["Kochen", "Autofahren", "Singen", "Tanzen", "Multitasking", "Witze erzaehlen"],
    "gen160": ["Bibliothek", "Kirche", "Krankenhaus", "Kino", "Beerdigung", "Gerichtssaal"],
    "gen161": ["Kerze", "Seife", "Parfuem", "Blumen", "Lotion", "Shampoo"],
    "gen162": ["Fernseher", "Laptop", "Handy", "Spielkonsole", "Spielzeug", "Kleidung"],
    "gen163": ["Stau", "Verschlafen", "Kinder", "Autopanne", "Wetter", "Keinen Parkplatz gefunden"],
    "gen164": ["Grillen", "Vaterwitze", "Nickerchen machen", "Thermostat", "Sport", "Rasenpflege"],
    "gen165": ["Chips", "Sellerie", "Apfel", "Muesli", "Suppe", "Popcorn"],
    "gen166": ["Suessigkeiten", "Getraenke", "Fast Food", "Chips", "Alkohol", "Handy"],
    "gen167": ["Schluessel", "Fernbedienung", "Handy", "Brille", "Socken", "Haargummis"],
    "gen168": ["Spinne", "Ameise", "Ratte", "Schlange", "Skorpion", "Katze"],
    "gen169": ["Eiscreme", "Schokolade", "Pizza", "Chips", "Fast Food", "Kekse"],
    "gen170": ["Essen nicht fertig", "Unordentliches Haus", "Nicht genug Essen", "Gaeste verstehen sich nicht", "Sitzordnung", "Getraenke gehen aus"],
    "gen171": ["Romantik", "Drama", "Krieg", "Animation", "Wahre Geschichte", "Sport"],
    "gen172": ["Schneemann bauen", "Ausschlafen", "Filme schauen", "Schneeballschlacht", "Heisse Schokolade trinken", "Schlittenfahren"],
    "gen173": ["Gesundheitsversorgung", "Wohnen", "Studium", "Benzin", "Lebensmittel", "Handyvertraege"],
    "gen174": ["Angst", "Insekt gesehen", "Schmerz", "Aufregung", "Wut", "Achterbahn"],
    "gen175": ["Schwimmen gehen", "Eis essen", "Klimaanlage einschalten", "Kaltes Wasser trinken", "Im Schatten sitzen", "Ventilator benutzen"],
    "gen176": ["Kumpel", "Alter", "Mann", "Herr oder Frau", "Hey du", "Typ"],
    "gen177": ["Musik", "Snacks", "Gute Gesellschaft", "Podcasts", "Schoene Strecke", "Haeufige Pausen"],
    "gen178": ["Batterien", "Klebeband", "Kugelschreiber", "Gummibaender", "Alte Schluessel", "Lieferservice-Menues"],
    "gen179": ["Kochen", "Kaempfen", "Renovieren", "Tanzen", "Vor Gefahr weglaufen", "Einparken"],
    "gen180": ["Wie gluecklich sie sind", "Ihr Aussehen", "Beziehungsstatus", "Einkommen oder Reichtum", "Was sie essen", "Ihr Alter"],
    "gen181": ["Lego", "Glas", "Reisszwecke", "Hundehaufen", "Insekt", "Kaugummi"],
    "gen182": ["Polizist", "Feuerwehrmann", "Arzt oder Krankenschwester", "Militaer", "Fast-Food-Mitarbeiter", "Pilot"],
    "gen183": ["Alte Kleidung", "Buecher", "Moebel", "Spielzeug", "Kuechensachen", "Elektronik"],
    "gen184": ["Wann heiratest du", "Zu viel essen", "Streit", "Fotos machen", "Tratsch", "Kinder rennen herum"],
    "gen185": ["Mais", "Kartoffeln", "Moehren", "Gruene Bohnen", "Brokkoli", "Erbsen"],
    "gen186": ["Handy", "Schluessel", "Portemonnaie", "Haare und Aussehen", "Tuer abgeschlossen", "Wetter"],
    "gen187": ["Romeo und Juliet", "Mickey und Minnie", "Barbie und Ken", "Shrek und Fiona", "Beauty and the Beast", "Jack und Rose"],
    "gen188": ["Wasser", "Limo", "Alkohol", "Schokolade", "Nuesse", "Chips"],
    "gen189": ["Schulbuecher", "Rucksack", "Altes Essen", "Jacke", "Spiegel", "Sportklamotten"],
    "gen190": ["Socken", "Putzmittel", "Diaetbuch", "Gutschein mit wenig Guthaben", "Deo", "Ein Buegeleisen"],
    "gen191": ["Schlange", "Igel", "Schwein", "Affe", "Vogelspinne", "Sugar Glider"],
    "gen192": ["Seid ruhig", "Buecher aufschlagen", "Passt auf", "Hausaufgaben abgeben", "Guten Morgen", "Keine Handys"],
    "gen193": ["Strassenbeleuchtung", "Freundliche Nachbarn", "Polizeipraesenz", "Saubere Strassen", "Wenig Kriminalitaet", "Ueberwachungskameras"],
    "gen194": ["Riesenrad", "Zuckerwatte", "Spiele", "Achterbahn", "Clowns", "Stofftiere"],
    "gen195": ["Abspuelen", "Zimmer aufraeumen", "Muell rausbringen", "Staubsaugen", "Rasen maehen", "Waesche"],
    "gen196": ["Wasser trinken", "Duschen", "Essen", "Dehnen", "In den Spiegel schauen", "Zusammenbrechen"],
    "gen197": ["Banane", "Sonne", "Schulbus", "Quietscheente", "Zitrone", "Taxi"],
    "gen198": ["Geld sparen", "Sport treiben", "Gesund essen", "Sprache lernen", "Reisen", "Lesen"],
    "gen199": ["Insektenspray", "Toilettenpapier", "Taschenlampe", "Streichhoelzer oder Feuerzeug", "Kissen", "Dosenoeffner"],
    "gen200": ["Jemanden kuessen", "Runterzaehlen", "Mit Sekt anstoessen", "Feuerwerk anschauen", "Frohes Neues rufen", "Sich etwas wuenschen"],
}
