# German answer text translations for gen201-gen300 (same order as English answers)
DE_ANSWER_TEXTS_NEW2 = {
    "gen201": ["Beyonce", "Oprah", "Madonna", "Adele", "Rihanna", "Cher"],
    "gen202": ["Aufs Handy schauen", "Auf die Stockwerknummern starren", "Schweigend dastehen", "Smalltalk machen", "Auf den Boden schauen", "Den Tuer-zu-Knopf druecken"],
    "gen203": ["Tomate", "Avocado", "Paprika", "Gurke", "Mais", "Kuerbis"],
    "gen204": ["Gewuerze und Sossen", "Reste", "Abgelaufene Sachen", "Kaese", "Natron", "Essiggurken"],
    "gen205": ["Jonglieren", "Rubik's Cube loesen", "Kartentricks", "Kugelschreiber drehen", "Mit Fingern pfeifen", "Moonwalking"],
    "gen206": ["Du bist so gross geworden", "Zu meiner Zeit", "Isst du genug", "Ich hab dich lieb", "Hast du einen Freund oder eine Freundin", "Sag es nicht deinen Eltern"],
    "gen207": ["Literally", "Ironic", "Irregardless", "Could care less", "Nauseous", "Peruse"],
    "gen208": ["Smalltalk", "Sport", "Arbeitsmeetings", "Anderer Leute Kinder", "Wein", "Netzwerk-Veranstaltungen"],
    "gen209": ["Schlange", "Spinne", "Baer", "Ratte", "Fledermaus", "Skorpion"],
    "gen210": ["Schluessel", "Handy", "Geldboerse", "Fernbedienung", "Socken", "Brille"],
    "gen211": ["Titanic", "The Notebook", "Twilight", "Mean Girls", "High School Musical", "Frozen"],
    "gen212": ["Klamotten", "Verpackungen", "Schuhe", "Teller oder Tassen", "Schulbuecher", "Ladekabel"],
    "gen213": ["Toilettenpapier", "Kondome", "Hygieneartikel", "Haemorrhoiden-Creme", "Durchfallmittel", "Erwachsenenwindeln"],
    "gen214": ["Personal Trainer", "Feuerwehrmann", "Sportler", "Militaer", "Rettungsschwimmer", "Taenzer"],
    "gen215": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "Baby Shark", "Twinkle Twinkle Little Star"],
    "gen216": ["Italien", "Japan", "Frankreich", "Australien", "Griechenland", "Island"],
    "gen217": ["Social Media scrollen", "Fernsehen", "Snacks essen", "Putzen", "Ein Nickerchen machen", "Online-Shopping"],
    "gen218": ["Frisch gebackene Kekse", "Play-Doh", "Sonnencreme", "Buntstifte", "Frisch gemaehtes Gras", "Omas Haus"],
    "gen219": ["In der Schlange warten", "Warten bis man dran ist", "Formulare ausfuellen", "Foto machen lassen", "Sehtest", "Alles"],
    "gen220": ["Golf", "Schwimmen", "Turnen", "Eislaufen", "Bowling", "Bogenschiessen"],
    "gen221": ["Alter", "Groesse", "Fotos", "Beruf", "Gewicht", "Hobbys"],
    "gen222": ["Fuetter mich", "Ich liebe dich", "Lass uns spazieren gehen", "Streichel mich", "Wer ist an der Tuer", "Wo warst du"],
    "gen223": ["Mental-Health-Tag", "Schoenes Wetter", "Kater", "Vorstellungsgespraech", "Familientermin", "Wollte nicht aufstehen"],
    "gen224": ["Rippchen", "Tacos", "Spaghetti", "Wings", "Maiskolben", "Wassermelone"],
    "gen225": ["Auto", "Handy", "Klimaanlage", "Internet", "Waschmaschine", "Toilette"],
    "gen226": ["Arzt", "Feuerwehrmann", "Astronaut", "Tierarzt", "Polizist", "YouTuber"],
    "gen227": ["Weihnachten", "Halloween", "Thanksgiving", "Ostern", "Valentinstag", "Vierter Juli"],
    "gen228": ["Kekse", "Brot", "Nudelsosse", "Kuchen", "Suppe", "Guacamole"],
    "gen229": ["Plastiktueten", "Klamotten", "Behaelter vom Lieferservice", "Ladekabel und Kabel", "Zeitschriften", "Gummibaender"],
    "gen230": ["iPhone-Klingelton", "Mikrowellen-Piepsen", "Tuerklopfen", "Autohupe", "Wecker", "Law & Order Sound"],
    "gen231": ["Google", "YouTube", "Facebook", "Amazon", "Wikipedia", "Netflix"],
    "gen232": ["Stau", "Wecker hat nicht geklingelt", "Autopanne", "Kinder", "Keinen Parkplatz gefunden", "Verfahren"],
    "gen233": ["Friseur", "Aufzug", "Zahnarzt", "Uber oder Taxi", "Familientreffen", "Wartezimmer"],
    "gen234": ["Politik", "Das letzte Stueck Kuchen", "Fernbedienung", "Wer besser gekocht hat", "Dunkles oder helles Fleisch", "Sitzordnung"],
    "gen235": ["Kosten", "Angst vor schlechten Nachrichten", "Spritzen", "Keine Zeit", "Langes Warten", "Peinlichkeit"],
    "gen236": ["Brokkoli", "Rosenkohl", "Spinat", "Erbsen", "Spargel", "Blumenkohl"],
    "gen237": ["Einen Wutanfall haben", "In der Nase bohren", "Nackt herumlaufen", "Mit Fremden reden", "Einen imaginaeren Freund haben", "Ueberall einschlafen"],
    "gen238": ["Batterien", "Kugelschreiber und Stifte", "Gummibaender", "Klebeband", "Schraubenzieher", "Lieferservice-Menues"],
    "gen239": ["TikTok", "Instagram", "Facebook", "YouTube", "Twitter", "Candy Crush"],
    "gen240": ["Ins Fitnessstudio gehen", "Gesuender essen", "Geld sparen", "Mit dem Rauchen aufhoeren", "Mehr Buecher lesen", "Eine neue Sprache lernen"],
    "gen241": ["Musik", "Snacks", "Gute Gesellschaft", "Schoene Aussicht", "An kuriosen Attraktionen anhalten", "Autospiele"],
    "gen242": ["Gesundheitskosten", "Studiengebuehren", "Wohnen", "Kinopopcorn", "Benzin", "Druckertinte"],
    "gen243": ["Schlange", "Affe", "Tiger", "Alligator", "Vogelspinne", "Frettchen"],
    "gen244": ["Kryptowaehrung", "Wein", "Moderne Kunst", "Der Aktienmarkt", "Automotoren", "Politik"],
    "gen245": ["Kuchen", "Luftballons", "Geschenke", "Kerzen", "Happy Birthday singen", "Partyhuete"],
    "gen246": ["Regen", "Gewitter", "Extreme Hitze", "Schnee", "Starker Wind", "Hagel"],
    "gen247": ["Um eine Gehaltserhoehung", "Um freie Tage", "Um Homeoffice", "Etwas nochmal zu erklaeren", "Nach einer Befoerderung", "Ob man frueher gehen darf"],
    "gen248": ["Schokolade", "Vanille", "Erdbeere", "Cookie Dough", "Minze-Schokostueckchen", "Karamell"],
    "gen249": ["Zaehne putzen", "Handy checken", "Aufs Klo gehen", "Wecker stellen", "Ein Buch lesen", "Tueren abschliessen"],
    "gen250": ["Monopoly", "Uno", "Risk", "Scrabble", "Sorry", "Clue"],
    "gen251": ["Urlaub", "Beziehungen", "Essen", "Fitness", "Neues Auto", "Kinder"],
    "gen252": ["Eiswagen", "Schulglocke", "Zeichentrick-Titelmelodie", "Mama ruft deinen Namen", "Videospielgeraeusche", "Seilspring-Lied"],
    "gen253": ["Polizist", "Spion", "Anwalt", "Hacker", "Arzt", "Archaeologe"],
    "gen254": ["Eis", "Nickerchen", "Zeichentrickfilme", "Schaukeln", "Geburtstagskuchen", "Luftpolsterfolie"],
    "gen255": ["Pommes und Eis", "Erdnussbutter und Essiggurken", "Pizza und Ranch", "Schokolade und Speck", "Scharfe Sosse und Obst", "Kaese und Honig"],
    "gen256": ["Naegel kauen", "Schwitzen", "Auf und ab gehen", "Herumzappeln", "Schnell reden", "Nervoes lachen"],
    "gen257": ["Fernseher", "Kleidung", "Spielzeug", "Elektronik", "Kuechengeraete", "Handtuecher"],
    "gen258": ["Schluessel", "Handy", "Geldboerse", "Fernbedienung", "Socken", "Sonnenbrille"],
    "gen259": ["Mental-Health-Tag", "Vorstellungsgespraech", "Schoenes Wetter", "Kater", "Sportveranstaltung", "Neues Videospiel"],
    "gen260": ["Suessigkeitenschale", "Spitzendeckchen", "Alte Fotos", "Plastikbezuege auf Moebeln", "Strickzeug", "Kuehlschrankmagnete"],
    "gen261": ["Morgan Freeman", "Arnold Schwarzenegger", "Christopher Walken", "Donald Trump", "Matthew McConaughey", "Elvis Presley"],
    "gen262": ["Social Media scrollen", "Jemandem schreiben", "Spiele spielen", "E-Mails checken", "Online-Shopping", "Videos schauen"],
    "gen263": ["Baer", "Loewe", "Hai", "Elefant", "Krokodil", "Stinktier"],
    "gen264": ["Diaet", "Sport", "Frueh aufstehen", "Mit dem Rauchen aufhoeren", "Geld sparen", "Mehr lesen"],
    "gen265": ["Bibliothek", "Kirche", "Krankenhaus", "Kino", "Beerdigung", "Gerichtssaal"],
    "gen266": ["Chips", "Pizza", "Wings", "Kuchen", "Kaese und Cracker", "Mini-Wuerstchen"],
    "gen267": ["Wein", "Autos", "Politik", "Technologie", "Kunst", "Klassische Musik"],
    "gen268": ["Popcorn", "Spinat", "Maiskolben", "Fleisch", "Karamell", "Sesamkoerner"],
    "gen269": ["The Lion King", "Titanic", "Star Wars", "Home Alone", "Wizard of Oz", "Forrest Gump"],
    "gen270": ["Autobahn", "Mitten im Nirgendwo", "Schlechte Gegend", "Bruecke", "Regensturm", "Beim Date"],
    "gen271": ["Kerzen", "Kaffee", "Parfuem", "Seife", "Vanilleextrakt", "Blumen"],
    "gen272": ["Puppen", "Kronkorken", "Loeffel", "Nagelreste", "Fast-Food-Spielzeug", "Steine"],
    "gen273": ["Ladekabel", "Zahnbuerste", "Unterwaesche", "Deo", "Medikamente", "Sonnencreme"],
    "gen274": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "ABC", "Jingle Bells"],
    "gen275": ["Kochen", "Golf", "Einparken", "Eislaufen", "Jonglieren", "Hula-Hoop"],
    "gen276": ["Stau", "Wecker hat nicht geklingelt", "Keinen Parkplatz gefunden", "Verfahren", "Kinder", "Autopanne"],
    "gen277": ["Batterien", "Gummibaender", "Kugelschreiber", "Klebeband", "Alte Menues", "Schraubenzieher"],
    "gen278": ["Schwimmen", "Tennis", "Fussball", "Golf", "Turnen", "Rudern"],
    "gen279": ["Grammatik", "Kindererziehung", "Essgewohnheiten", "Mode", "Fahrweise", "Musikgeschmack"],
    "gen280": ["Auf den Bildschirm starren", "Ein Klemmbrett tragen", "Schnell gehen", "Am Telefon reden", "Papiere sortieren", "E-Mails schreiben"],
    "gen281": ["Hundebellen", "Katzenmiauzen", "Kuhmuhen", "Entenquaken", "Hahnkraehen", "Schlangenzischen"],
    "gen282": ["Besuch bei der Zulassungsstelle", "Arzttermin", "Lebensmitteleinkauf", "Flughafensicherheit", "Software-Updates", "Moebel zusammenbauen"],
    "gen283": ["Thanksgiving", "Valentinstag", "Weihnachten", "Silvester", "Muttertag", "Erster April"],
    "gen284": ["Toilette", "Erotikgeschaeft", "Arztpraxis", "Therapeut", "Pfandleiher", "Kautionsbuero"],
    "gen285": ["Auto", "Handy", "Toilette", "Klimaanlage", "Computer", "Reissverschluss"],
    "gen286": ["Definitely", "Necessary", "Restaurant", "Accommodate", "Occurrence", "Wednesday"],
    "gen287": ["Musik", "Snacks", "Gute Gesellschaft", "Autospiele", "Schoene Strecke", "Hoerbuecher"],
    "gen288": ["Schmutzige Waesche", "Handy", "Poster", "Videospiele", "Leere Essensbehaelter", "Kopfhoerer"],
    "gen289": ["Der Weihnachtsmann ist echt", "Gemuese macht stark", "Der Hund ist auf einen Bauernhof gezogen", "Der Eiswagen ist ausverkauft", "Das tut nicht weh", "Wenn du schielst, bleiben die Augen so"],
    "gen290": ["Kekse", "Brot", "Nudelsosse", "Kuchen", "Suppe", "Limonade"],
    "gen291": ["Toilettenpapier", "Plastiktueten", "Klamotten", "Buecher", "Behaelter vom Lieferservice", "Gutscheine"],
    "gen292": ["Bettwanzen", "Haare", "Versteckte Kamera", "Flecken", "Schimmel", "Jemand anderes"],
    "gen293": ["Gitarre spielen", "Tanzen", "Kartentricks", "Singen", "Kochen", "Jonglieren"],
    "gen294": ["Singen", "Nachdenken", "Weinen", "Mit sich selbst streiten", "Zaehne putzen", "Pinkeln"],
    "gen295": ["Monopoly", "Uno", "Mario Kart", "Risk", "Settlers of Catan", "Pictionary"],
    "gen296": ["Smalltalk", "Salat", "Wein", "Sport", "Frueh aufstehen", "Klassische Musik"],
    "gen297": ["Feuerwehrmann", "Militaer", "Polizist", "Pilot", "Arzt", "Astronaut"],
    "gen298": ["Burger", "Steak", "Pommes", "Pasta", "Fruehstueck", "Salat"],
    "gen299": ["Steuererklaerung", "Geld verwalten", "Kochen", "Reparaturen", "Kommunikationsfaehigkeiten", "Erste Hilfe"],
    "gen300": ["Essen", "Eine Umarmung", "Musik", "Nickerchen", "Haustier", "Kompliment"],
}
