# German answer text translations (same order as English answers)
DE_ANSWER_TEXTS = {
    "q001": ["Handtuch", "Sonnencreme", "Sonnenschirm", "Kuehlbox", "Stuhl", "Sonnenbrille"],
    "q002": ["Erkaeltung oder Grippe", "Kopfschmerzen", "Bauchschmerzen", "Mental-Health-Tag", "Rueckenschmerzen", "Zahnarzttermin"],
    "q003": ["Kreditkarte", "Bargeld", "Ausweis", "Fotos", "Quittungen", "Visitenkarten"],
    "q004": ["Social Media", "Schreiben", "Spiele spielen", "Videos schauen", "E-Mails checken", "Nachrichten lesen"],
    "q005": ["Peperoniwurst", "Pilze", "Wurst", "Zwiebeln", "Paprika", "Oliven"],
    "q006": ["Zahnbuerste", "Ladegeraet", "Unterwaesche", "Medikamente", "Deo", "Schlafanzug"],
    "q007": ["Spinnen", "Hoehen", "Schlangen", "Oeffentliches Reden", "Dunkelheit", "Fliegen"],
    "q008": ["Zaehne putzen", "Handy checken", "Fernsehen", "Lesen", "Duschen", "Wecker stellen"],
    "q009": ["Mehr Sport", "Abnehmen", "Geld sparen", "Aufhoeren zu rauchen", "Mehr lesen", "Mehr reisen"],
    "q010": ["Schreibtisch", "Whiteboard", "Stuhl", "Buecher", "Computer", "Uhr"],
    "q011": ["Fussball", "Basketball", "Baseball", "Tennis", "Eishockey", "Golf"],
    "q012": ["Ketchup", "Kaese", "Salat", "Tomate", "Zwiebel", "Gurken"],
    "q013": ["Bett", "Fernseher", "Bibel", "Handtuecher", "Minibar", "Safe"],
    "q014": ["Hai", "Delfin", "Wal", "Oktopus", "Meeresschildkroete", "Qualle"],
    "q015": ["Briefmarken", "Muenzen", "Karten", "Kunst", "Schallplatten", "Schuhe"],
    "q016": ["Stau", "Verschlafen", "Kinder", "Autopanne", "Schlechtes Wetter", "Schluessel verloren"],
    "q017": ["Eier", "Toast", "Muesli", "Pfannkuchen", "Speck", "Obst"],
    "q018": ["Los geht's", "Schiri ist blind", "Tor", "Buh", "Abwehr", "MVP"],
    "q019": ["Tanzen", "Trinken", "Mit Leuten reden", "Essen", "Spiele spielen", "Fotos machen"],
    "q020": ["Sonnenbrille", "Ladegeraet", "Wasserflasche", "Ersatzreifen", "Fahrzeugschein", "Regenschirm"],
    "q021": ["Vorsorge", "Erkaeltung oder Grippe", "Schmerzen", "Rezept", "Verletzung", "Impfung"],
    "gen001": ["Milch", "Brot", "Eier", "Butter", "Obst", "Toilettenpapier"],
    "gen002": ["Fernsehen", "Am Handy scrollen", "Schlafen", "Essen", "Putzen", "Videospiele spielen"],
    "gen003": ["Brokkoli", "Rosenkohl", "Spinat", "Erbsen", "Blumenkohl", "Spargel"],
    "gen004": ["The Lion King", "Titanic", "Harry Potter", "Star Wars", "Shrek", "Frozen"],
    "gen005": ["Smalltalk", "Das Essen", "Witze vom Chef", "Teambuilding-Spiele", "Tanzen", "Dort sein"],
    "gen006": ["Italien", "Japan", "Frankreich", "Griechenland", "Australien", "Malediven"],
    "gen007": ["Kerzen ausblasen", "Kuchen essen", "Geschenke oeffnen", "Party feiern", "Sich etwas wuenschen", "Happy Birthday singen"],
    "gen008": ["Handy", "Auto", "WLAN", "Waschmaschine", "Toilette", "Klimaanlage"],
    "gen009": ["Golf", "Schwimmen", "Turnen", "Bowling", "Eislaufen", "Bogenschiessen"],
    "gen010": ["Baer", "Stinktier", "Affe", "Elefant", "Papagei", "Ziege"],
    "gen011": ["Definitely", "Restaurant", "Necessary", "Separate", "Embarrassed", "Wednesday"],
    "gen012": ["Ihr Alter", "Ihren Job", "Ihre Hobbys", "Wie viel sie trinken", "Ihre Ex-Beziehungen", "Ihre Groesse"],
    "gen013": ["Haare faerben", "Sport treiben", "Schminken", "Botox", "Juenger kleiden", "Hautpflege"],
    "gen014": ["Vogelgesang", "Regen", "Meereswellen", "Wind", "Grillen", "Wasserfall"],
    "gen015": ["Batterien", "Kugelschreiber", "Gummibaender", "Schluessel", "Klebeband", "Lieferservice-Menues"],
    "gen016": ["Rippchen", "Spaghetti", "Tacos", "Wings", "Maiskolben", "Burrito"],
    "gen017": ["Friends", "The Office", "Stranger Things", "Breaking Bad", "Grey's Anatomy", "Game of Thrones"],
    "gen018": ["Fernsehen", "Social Media scrollen", "Putzen", "Essen", "Nickerchen", "Mit Freunden reden"],
    "gen019": ["Lange Schlangen", "Verspaetungen", "Enge Sitze", "Schreiende Babys", "Verlorenes Gepaeck", "Turbulenzen"],
    "gen020": ["Steuererklaerung", "Hausaufgaben", "Packen", "Weihnachtseinkauf", "Waesche", "Putzen"],
    "gen021": ["Bier", "Margarita", "Whiskey", "Wodka Soda", "Wein", "Old Fashioned"],
    "gen022": ["Morgan Freeman", "Arnold Schwarzenegger", "Christopher Walken", "Donald Trump", "Matthew McConaughey", "Owen Wilson"],
    "gen023": ["Stress", "Handy", "Laerm", "Kaffee", "Schmerzen", "Albtraum"],
    "gen024": ["Zu muede", "Keine Zeit", "Zu teuer", "Schlechtes Wetter", "Verletzung", "Zu faul"],
    "gen025": ["Musik", "Navigation", "Temperatur", "Wo essen", "Wer faehrt", "Pinkelpausen"],
    "gen026": ["Abspuelen", "Bad putzen", "Waesche", "Staubsaugen", "Muell rausbringen", "Rasen maehen"],
    "gen027": ["Popcorn", "Suessigkeiten", "Nachos", "Hot Dog", "Limo", "Eis"],
    "gen028": ["Handy", "Zettel", "Kaugummi", "Spielzeug", "Muetze", "Kopfhoerer"],
    "gen029": ["Nilpferd", "Delfin", "Schwan", "Elch", "Koala", "Schnabeltier"],
    "gen030": ["Parfuem", "Kaffee", "Kerzen", "Seife", "Blumen", "Vanilleextrakt"],
    "gen031": ["Sherlock Holmes", "Batman", "Scooby-Doo", "Inspector Gadget", "Nancy Drew", "Hercule Poirot"],
    "gen032": ["Der Geruch", "Einrichtung", "Sauberkeit", "Die Kueche", "Haustiere", "Fotos"],
    "gen033": ["Karten", "Scharade", "Monopoly", "Scrabble", "Quizspiele", "Pictionary"],
    "gen034": ["Krankheitssymptome", "Sich selbst", "Promi-Klatsch", "Wie man ein Wort schreibt", "Den Ex", "Dumme Fragen"],
    "gen035": ["Kondome", "Toilettenpapier", "Damenhygieneprodukte", "Abfuehrmittel", "Erwachsenenwindeln", "Juckreizcreme"],
    "gen036": ["Eiffelturm", "Freiheitsstatue", "Chinesische Mauer", "Big Ben", "Pyramiden", "Taj Mahal"],
    "gen037": ["Steuern", "Kryptowaehrung", "Politik", "Automotoren", "Wein", "Aktienmarkt"],
    "gen038": ["Ueber den Ex reden", "Am Handy sein", "Zu spaet kommen", "Unordentlich essen", "Ueber Heirat reden", "Ruelpsen"],
    "gen039": ["Rosen", "Tulpen", "Sonnenblumen", "Lilien", "Orchideen", "Gaensebluemchen"],
    "gen040": ["Nuggets", "Wings", "Pocken", "Suppe", "Finger", "Brust"],
    "gen041": ["Bellende Hunde", "Baustelle", "Rasenmaeher", "Verkehr", "Partys", "Spielende Kinder"],
    "gen042": ["Eis", "Schokolade", "Kaese-Makkaroni", "Pizza", "Chips", "Suppe"],
    "gen043": ["Arzt", "Astronaut", "Feuerwehrmann", "Polizist", "Sportler", "Tierarzt"],
    "gen044": ["Handy", "Haustiere", "Familienfotos", "Geldbeutel", "Dokumente", "Laptop"],
    "gen045": ["Mango", "Wassermelone", "Granatapfel", "Orange", "Pfirsich", "Grapefruit"],
    "gen046": ["Grey's Anatomy", "House", "ER", "Scrubs", "The Good Doctor", "Chicago Med"],
    "gen047": ["Tuer abschliessen", "Schluessel nehmen", "Licht ausschalten", "Handy nehmen", "Herd ausschalten", "Geldbeutel nehmen"],
    "gen048": ["Nicht gesehen", "Akku leer", "War beschaeftigt", "Vergessen", "Eingeschlafen", "Schlechter Empfang"],
    "gen049": ["Golf", "Laufen", "Schwimmen", "Tennis", "Bowling", "Radfahren"],
    "gen050": ["Schwein", "Kraehe", "Oktopus", "Hund", "Ratte", "Elefant"],
    "gen051": ["Kugelschreiber", "Feuerzeug", "Regenschirm", "Buecher", "Ladegeraet", "Tupperware"],
    "gen052": ["Steuererklaerung machen", "Budgetplanung", "Kochen", "Erste Hilfe", "Autowartung", "Wie man waehlt"],
    "gen053": ["Bibliothek", "Kirche", "Kino", "Krankenhaus", "Beerdigung", "Klassenzimmer"],
    "gen054": ["Pizza", "Lasagne", "Chinesisches Essen", "Chili", "Eintopf", "Thanksgiving-Truthahn"],
    "gen055": ["Darth Vader", "Joker", "Thanos", "Voldemort", "Cruella de Vil", "Scar"],
    "gen056": ["Warten in der Schlange", "Papierkram", "Foto", "Sehtest", "Schriftliche Pruefung", "Aufgerufen werden"],
    "gen057": ["Klavier", "Gitarre", "Geige", "Schlagzeug", "Saxophon", "Harfe"],
    "gen058": ["Musik hoeren", "Hupen", "Handy checken", "Singen", "Fluchen", "Podcast"],
    "gen059": ["Was essen", "Thermostat", "Abspuelen", "Fernbedienung", "Toilettendeckel", "Schnarchen"],
    "gen060": ["Couch", "Auto", "Waesche", "Schlafzimmer", "Flughafen", "Fitnessstudio"],
    "gen061": ["Regen", "Schnee", "Hurrikan", "Extreme Hitze", "Gewitter", "Nebel"],
    "gen062": ["Suessigkeiten", "Stricken", "Alte Fotos", "Deckchen", "Vitrinenschrank", "Katzen"],
    "gen063": ["Verfolgungsjagd", "Explosion", "Kampfszene", "Schiesserei", "Cooler Spruch", "Held geht davon"],
    "gen064": ["Fitnessstudio-Mitgliedschaft", "Kochbuecher", "Laufband", "Buecher", "Entsafter", "Buegeleisen"],
    "gen065": ["Zahnseide benutzen", "Zweimal taeglich putzen", "Mundspuelung benutzen", "Weniger Zucker", "In 6 Monaten wiederkommen", "Zahnbuerste wechseln"],
    "gen066": ["Bohemian Rhapsody", "Happy Birthday", "Don't Stop Believin'", "Sweet Caroline", "Mr. Brightside", "Baby Shark"],
    "gen067": ["Essen", "Wasser", "Kaffee", "Souvenirs", "Parken", "WLAN"],
    "gen068": ["Monopoly", "Risiko", "Uno", "Scrabble", "Sorry", "Settlers of Catan"],
    "gen069": ["Im Internet surfen", "Handy checken", "Mit Kollegen quatschen", "Lange Pause machen", "Nickerchen", "Frueher gehen"],
    "gen070": ["Kekse", "Brot", "Tomatensosse", "Kuchen", "Suppe", "Limonade"],
    "gen071": ["Gitarre spielen", "Zaubertricks", "Tanzen", "Jonglieren", "Singen", "Barkeeping"],
    "gen072": ["Handy", "Klamotten auf dem Boden", "Poster", "Spielkonsole", "Kopfhoerer", "Leere Snacktueten"],
    "gen073": ["Hubschrauber", "Lamborghini", "Heissluftballon", "Yacht", "Privatjet", "U-Boot"],
    "gen074": ["Weihnachten", "Valentinstag", "Thanksgiving", "Black Friday", "Hochzeitstag", "Ostern"],
    "gen075": ["Faxgeraet", "Videorekorder", "CD-Player", "Pager", "Diskette", "Klapphandy"],
    "gen076": ["Turnen", "Stabhochsprung", "Turmspringen", "Eiskunstlauf", "Gewichtheben", "Fechten"],
    "gen077": ["Faultier", "Schildkroete", "Schnecke", "Koala", "Seekuh", "Seestern"],
    "gen078": ["Handy checken", "Auf die Toilette gehen", "Zaehne putzen", "Kaffee machen", "Strecken", "Schlummertaste druecken"],
    "gen079": ["Cowboys", "BBQ", "Waffen", "Grosse Trucks", "Oel", "Steaks"],
    "gen080": ["Kaffeemaschine", "Drucker", "Computer", "Tacker", "Whiteboard", "Uhr"],
    "gen081": ["Geister", "Gruselige Geraeusche", "Dunkelheit", "Schockmomente", "Spinnen", "Clowns"],
    "gen082": ["Geht aus", "Autokorrektur", "Spam-Anrufe", "Updates", "Benachrichtigungen", "Haengt sich auf"],
    "gen083": ["Basketball", "Fussball", "Football", "Volleyball", "Eishockey", "Rudern"],
    "gen084": ["Hai", "Schlange", "Fledermaus", "Wolf", "Spinne", "Hyaene"],
    "gen085": ["Spiegel zerbrechen", "Schwarze Katze", "Unter Leiter durchgehen", "Zahl 13", "Regenschirm drinnen oeffnen", "Salz verschuetten"],
    "gen086": ["Magnete", "Postkarten", "Schnapsglaeser", "T-Shirts", "Schluesselanhaenger", "Schneekugeln"],
    "gen087": ["Firma recherchieren", "Schick anziehen", "Antworten ueben", "Duschen", "Lebenslauf drucken", "Anfahrt planen"],
    "gen088": ["Wein", "Kaese", "Whiskey", "Jeans", "Gusseisenpfanne", "Balsamico-Essig"],
    "gen089": ["Jemand weint", "Eroeffnungstanz", "Torte anschneiden", "Brautstrauss werfen", "Reden", "Jemand wird betrunken"],
    "gen090": ["Eiche", "Palme", "Kiefer", "Ahorn", "Birke", "Weide"],
    "gen091": ["Work", "Sick", "Coming", "Town", "Made", "Land"],
    "gen092": ["Zelt", "Lagerfeuer", "Schlafsack", "Marshmallows", "Insektenspray", "Kuehlbox"],
    "gen093": ["Fruechte-Kuchen", "Eierlikoerpunsch", "Preiselbeersosse", "Suesskartoffeln", "Fuellung", "Mince Pie"],
    "gen094": ["123456", "Password", "Ihr Geburtstag", "Name des Haustiers", "Qwerty", "Ihr Name"],
    "gen095": ["Burpees", "Laufen", "Planks", "Kniebeugen", "Liegestuetze", "Ausfallschritte"],
    "gen096": ["Eichhoernchen", "Vogel", "Kaninchen", "Reh", "Waschbaer", "Katze"],
    "gen097": ["Birth", "To", "Holi", "Every", "Sun", "Pay"],
    "gen098": ["Alte Zeitschriften", "Unbequeme Stuehle", "Fernseher", "Aquarium", "Desinfektionsmittel", "Weinende Kinder"],
    "gen099": ["Kaenguru", "Koala", "Sydney Opera House", "Krokodil", "Vegemite", "Great Barrier Reef"],
    "gen100": ["Feuer", "Autounfall", "Ueberfall", "Herzinfarkt", "Schlaegerei", "Verdaechtige Person"],
}
