# German question text translations for gen201-gen300
DE_QUESTIONS_NEW2 = {
    "gen201": "Nenne einen Star, den jeder nur beim Vornamen erkennt.",
    "gen202": "Was machen Leute, wenn eine Aufzugfahrt unangenehm ist?",
    "gen203": "Nenne ein Lebensmittel, bei dem man streitet, ob es Obst oder Gemuese ist.",
    "gen204": "Nenne etwas, das immer hinten im Kuehlschrank steht.",
    "gen205": "Nenne eine Faehigkeit, die nutzlos aber beeindruckend ist.",
    "gen206": "Nenne etwas, das Grosseltern immer sagen.",
    "gen207": "Nenne ein Wort, das Leute haeufig falsch benutzen.",
    "gen208": "Nenne etwas, das Leute vortaeuschen zu moegen, aber heimlich hassen.",
    "gen209": "Nenne ein Tier, vor dem du Angst haettest, es in deinem Haus zu finden.",
    "gen210": "Nenne etwas, das Leute staendig verlieren.",
    "gen211": "Nenne einen Film, den jeder gesehen hat, aber keiner zugibt ihn zu lieben.",
    "gen212": "Nenne etwas, das man auf dem Boden eines unordentlichen Teenagerzimmers findet.",
    "gen213": "Nenne etwas, das Leuten peinlich ist im Laden zu kaufen.",
    "gen214": "Nenne einen Beruf, bei dem man erwartet, dass die Person fit ist.",
    "gen215": "Nenne ein Lied, bei dem jeder den Text kennt.",
    "gen216": "Nenne ein Land, das Leute traeumen eines Tages zu besuchen.",
    "gen217": "Was machen Leute, um zu prokrastinieren?",
    "gen218": "Nenne einen Geruch, der sofort Kindheitserinnerungen weckt.",
    "gen219": "Nenne etwas, das bei der Zulassungsstelle ewig dauert.",
    "gen220": "Nenne eine Sportart, die einfach aussieht, aber richtig schwer ist.",
    "gen221": "Nenne etwas, worueber Leute auf ihrem Dating-Profil luegen.",
    "gen222": "Nenne etwas, das ein Hund sagen wuerde, wenn er reden koennte.",
    "gen223": "Nenne einen Grund, warum Leute sich krank melden, obwohl sie nicht krank sind.",
    "gen224": "Nenne ein Essen, das unmoeglich sauber zu essen ist.",
    "gen225": "Nenne etwas, das immer im schlechtesten Moment kaputt geht.",
    "gen226": "Nenne einen Beruf, den Kinder ausueben wollen wenn sie gross sind.",
    "gen227": "Nenne einen Feiertag, fuer den Leute viel zu frueh anfangen sich vorzubereiten.",
    "gen228": "Nenne etwas, das selbstgemacht besser ist als gekauft.",
    "gen229": "Nenne etwas, das Leute horten, obwohl sie es nicht brauchen.",
    "gen230": "Nenne ein Geraeusch, das sofort erkennbar ist.",
    "gen231": "Nenne eine Webseite, die jeder mindestens einmal besucht hat.",
    "gen232": "Nenne eine Ausrede, die Leute fuers Zuspaet-Kommen haben.",
    "gen233": "Nenne einen Ort, an dem man gezwungen ist, unangenehmen Smalltalk zu machen.",
    "gen234": "Nenne etwas, worueber Leute an Thanksgiving streiten.",
    "gen235": "Nenne einen Grund, warum Leute es vermeiden zum Arzt zu gehen.",
    "gen236": "Nenne ein Gemuese, das Kinder sich weigern zu essen.",
    "gen237": "Nenne etwas, das fuer Kinder akzeptabel ist, aber fuer Erwachsene seltsam waere.",
    "gen238": "Nenne etwas, das man in einer Kramschublade findet.",
    "gen239": "Nenne eine App, nach der Leute suechtig sind.",
    "gen240": "Nenne etwas, das Leute an Silvester vornehmen, aber nie tun.",
    "gen241": "Nenne etwas, das einen Roadtrip lustig macht.",
    "gen242": "Nenne etwas, das viel teurer ist als es sein sollte.",
    "gen243": "Nenne ein Tier, das Leute als Haustier halten, aber wahrscheinlich nicht sollten.",
    "gen244": "Nenne etwas, von dem du so tust als wuerdest du es verstehen, aber eigentlich nicht.",
    "gen245": "Nenne etwas, das man auf jeder Geburtstagsfeier findet.",
    "gen246": "Nenne eine Wetterlage, die Plaene im Freien ruiniert.",
    "gen247": "Nenne etwas, das Leute sich nicht trauen ihren Chef zu fragen.",
    "gen248": "Nenne eine Eissorte, die fast jeder mag.",
    "gen249": "Nenne etwas, das Leute direkt vor dem Schlafengehen tun.",
    "gen250": "Nenne ein Brettspiel, das die meisten Familienstreits verursacht.",
    "gen251": "Nenne etwas, womit Leute auf Social Media angeben.",
    "gen252": "Nenne ein Geraeusch, das dich sofort in die Kindheit zurueckversetzt.",
    "gen253": "Nenne einen Beruf, den Filme viel cooler aussehen lassen als er ist.",
    "gen254": "Nenne etwas, fuer das man nie zu alt ist.",
    "gen255": "Nenne eine Essenskombination, die komisch klingt aber gut schmeckt.",
    "gen256": "Nenne etwas, das Leute tun wenn sie nervoes sind.",
    "gen257": "Nenne einen Gegenstand, um den Leute beim Ausverkauf kaempfen.",
    "gen258": "Was verlieren Leute staendig?",
    "gen259": "Nenne einen Grund, sich krank zu melden, obwohl man nicht krank ist.",
    "gen260": "Nenne etwas, das man in jeder Oma-Wohnung findet.",
    "gen261": "Nenne einen Star, den jeder nachmachen kann.",
    "gen262": "Nenne etwas, das Leute auf dem Handy tun, waehrend sie so tun als wuerden sie zuhoeren.",
    "gen263": "Nenne ein Tier, das als Haustier schrecklich waere.",
    "gen264": "Nenne etwas, das Leute immer sagen, am Montag anzufangen.",
    "gen265": "Nenne einen Ort, an dem Leute immer fluestern.",
    "gen266": "Nenne ein Essen, das Leute auf einer Party viel zu viel davon essen.",
    "gen267": "Nenne etwas, von dem Leute so tun als wuessten sie Bescheid, aber eigentlich nicht.",
    "gen268": "Nenne etwas, das immer in den Zaehnen stecken bleibt.",
    "gen269": "Welchen Film hat jeder mindestens einmal gesehen?",
    "gen270": "Nenne einen Ort, an dem du ungern eine Reifenpanne haettest.",
    "gen271": "Was riecht gut, schmeckt aber schrecklich?",
    "gen272": "Nenne etwas, das Leute sammeln und andere komisch finden.",
    "gen273": "Nenne etwas, das man immer vergisst fuer eine Reise einzupacken.",
    "gen274": "Nenne ein Lied, bei dem jeder den Text kennt.",
    "gen275": "Was ist schwieriger als es aussieht?",
    "gen276": "Nenne eine Ausrede fuer Verspaetung.",
    "gen277": "Was versteckt sich immer in einer Kramschublade?",
    "gen278": "Nenne eine Sportart, die einfach aussieht, aber anstrengend ist.",
    "gen279": "Nenne etwas, wofuer du andere heimlich verurteilst.",
    "gen280": "Nenne etwas, das Leute tun, um auf der Arbeit beschaeftigt auszusehen.",
    "gen281": "Nenne ein Tiergeraeusch, das jeder nachmachen kann.",
    "gen282": "Was dauert viel laenger als es sollte?",
    "gen283": "Welchen Feiertag fuerchten Leute heimlich?",
    "gen284": "Wonach fragen Leute ungern nach dem Weg?",
    "gen285": "Was geht immer im schlechtesten Moment kaputt?",
    "gen286": "Nenne ein Wort, das Leute haeufig falsch schreiben.",
    "gen287": "Nenne etwas, das einen Roadtrip lustiger macht.",
    "gen288": "Was findet man in einem Teenagerzimmer?",
    "gen289": "Nenne eine Luege, die Eltern ihren Kindern erzaehlen.",
    "gen290": "Nenne etwas, das selbstgemacht besser ist als gekauft.",
    "gen291": "Was horten Leute, obwohl sie es nicht brauchen?",
    "gen292": "Nenne etwas, das du ungern in deinem Hotelzimmer entdecken wuerdest.",
    "gen293": "Nenne eine Faehigkeit, die Leute auf einer Party beeindruckt.",
    "gen294": "Was machen Leute unter der Dusche ausser sich zu waschen?",
    "gen295": "Nenne ein Spiel, das Freundschaften zerstoert hat.",
    "gen296": "Was tust du als Erwachsener so, als wuerdest du es geniessen?",
    "gen297": "Nenne einen Beruf mit einer coolen Uniform.",
    "gen298": "Nenne etwas, das im Restaurant immer besser schmeckt.",
    "gen299": "Nenne etwas, das Leute wuenschen in der Schule gelernt zu haben.",
    "gen300": "Was macht einen schlechten Tag sofort besser?",
}
