# German question text translations for gen101-gen200
DE_QUESTIONS_NEW1 = {
    "gen101": "Nenne ein Essen, das man unmoeglich leise essen kann.",
    "gen102": "Nenne etwas, bei dem Leute auf Dinnerpartys so tun, als wuerden sie es verstehen.",
    "gen103": "Nenne einen Film, bei dem immer geweint wird.",
    "gen104": "Nenne etwas, das besser riecht als es schmeckt.",
    "gen105": "Nenne etwas, das Touristen in einem neuen Land immer falsch machen.",
    "gen106": "Nenne ein Tier, das suess aussieht, aber eigentlich gefaehrlich ist.",
    "gen107": "Nenne etwas, das Leute staendig im eigenen Haus verlieren.",
    "gen108": "Nenne einen Beruf, den Kinder spaeter ausueben wollen.",
    "gen109": "Nenne etwas, das Leute tun, um zu prokrastinieren.",
    "gen110": "Nenne ein Wort, das Leute oft falsch schreiben.",
    "gen111": "Nenne etwas, das Leute immer vergessen einzupacken.",
    "gen112": "Nenne etwas, das immer bei Oma im Haus ist.",
    "gen113": "Nenne eine Ausrede, um frueh von einer Party zu gehen.",
    "gen114": "Nenne etwas, woreuber Leute auf Roadtrips streiten.",
    "gen115": "Nenne eine Sportart, die langweilig zum Zuschauen, aber spassig zum Spielen ist.",
    "gen116": "Nenne etwas, woreuber Leute beim ersten Date luegen.",
    "gen117": "Nenne etwas, das beim Arzt ewig dauert.",
    "gen118": "Nenne eine Hausarbeit, die jeder hasst.",
    "gen119": "Nenne ein Geraeusch, das dich mitten in der Nacht aufweckt.",
    "gen120": "Nenne etwas, das Leute tun, wenn sie im Aufzug feststecken.",
    "gen121": "Nenne einen beruehmten fiktiven Detektiv.",
    "gen122": "Nenne etwas, wo man immer lange anstehen muss.",
    "gen123": "Nenne etwas, das man in einer Kramschublade findet.",
    "gen124": "Nenne ein Lied, von dem jeder den Text kennt.",
    "gen125": "Nenne etwas, das Leute immer sagen, dass sie es tun werden, aber nie machen.",
    "gen126": "Nenne ein Gemuese, das Kinder nicht essen wollen.",
    "gen127": "Nenne etwas, das Leute vor dem Verlassen des Hauses checken.",
    "gen128": "Nenne eine beruehmte Sehenswuerdigkeit, vor der Leute Fotos machen.",
    "gen129": "Nenne etwas, das Leute tun, wenn ihr Lieblingslied kommt.",
    "gen130": "Nenne ein haeufig verwendetes Passwort.",
    "gen131": "Nenne ein Tier, das man in jemandes Garten sehen koennte.",
    "gen132": "Nenne etwas, das sich immer verheddert.",
    "gen133": "Nenne etwas, das Leute sich im Restaurant nicht trauen zu bestellen.",
    "gen134": "Nenne einen Feiertag, an dem viel gekocht wird.",
    "gen135": "Nenne etwas, das am Flughafen immer teurer ist.",
    "gen136": "Nenne einen Grund, warum jemand kurzfristig Plaene absagt.",
    "gen137": "Nenne etwas, das Leute sammeln.",
    "gen138": "Nenne einen Ort, an dem man fluestern muss.",
    "gen139": "Nenne ein Spiel, das man beim Grillen spielt.",
    "gen140": "Nenne etwas, das mit Handschuhen schwer zu machen ist.",
    "gen141": "Nenne einen fiktiven Ort, den sich jeder als real wuenscht.",
    "gen142": "Nenne etwas, das Leute ins Kino schmuggeln.",
    "gen143": "Nenne etwas, das immer im schlechtesten Moment kaputt geht.",
    "gen144": "Nenne eine Frucht, die Leute in Getraenke tun.",
    "gen145": "Nenne etwas, das Leute tun, waehrend sie im Restaurant aufs Essen warten.",
    "gen146": "Nenne eine Serie, die Leute am Stueck durchschauen.",
    "gen147": "Nenne etwas, das man auf dem Lehrertisch findet.",
    "gen148": "Nenne etwas, das furchtbar riecht, aber trotzdem gegessen wird.",
    "gen149": "Nenne etwas, das Leute in ihrer Mittagspause auf der Arbeit tun.",
    "gen150": "Nenne ein Brettspiel, das zu Familienstreit fuehrt.",
    "gen151": "Nenne etwas, das eine Katze vom Tisch wirft.",
    "gen152": "Nenne ein Geraeusch, das schwer zu ignorieren ist.",
    "gen153": "Nenne etwas, das Leute tun, waehrend sie im Restaurant auf ihr Essen warten.",
    "gen154": "Nenne einen Grund, warum Leute ein Selfie machen.",
    "gen155": "Nenne etwas, das immer im schlechtesten Moment leer wird.",
    "gen156": "Nenne ein Essen, das besser schmeckt, wenn jemand anderes es macht.",
    "gen157": "Nenne etwas, das man in jedem Badezimmer findet.",
    "gen158": "Nenne etwas, bei dem Leute so tun, als haetten sie es gelesen.",
    "gen159": "Nenne etwas, bei dem Leute immer behaupten, gut darin zu sein, es aber meistens nicht sind.",
    "gen160": "Nenne einen Ort, an dem man leise sein muss.",
    "gen161": "Nenne etwas, das gut riecht, aber nicht gegessen werden sollte.",
    "gen162": "Nenne einen Artikel, um den sich Leute am Black Friday streiten.",
    "gen163": "Nenne einen Grund, warum Leute zu spaet zur Arbeit kommen.",
    "gen164": "Nenne etwas, das jeder Papa zu lieben scheint.",
    "gen165": "Nenne ein Essen, das unmoeglich leise zu essen ist.",
    "gen166": "Nenne etwas, das Leute ins Kino reinschmuggeln.",
    "gen167": "Nenne etwas, das Leute immer in ihrem Haus verlieren.",
    "gen168": "Nenne ein Tier, das erschreckend waere, wenn es so gross wie ein Pferd waere.",
    "gen169": "Nenne ein Essen, das Leute bei Stress essen.",
    "gen170": "Nenne etwas, woreuber Leute in Panik geraten, wenn sie eine Dinnerparty geben.",
    "gen171": "Nenne ein Filmgenre, bei dem Leute weinen.",
    "gen172": "Nenne etwas, das Leute an einem Schneetag machen.",
    "gen173": "Nenne etwas, das viel teurer ist als es sein sollte.",
    "gen174": "Nenne einen Grund, warum jemand schreien wuerde.",
    "gen175": "Nenne etwas, das Leute tun, um sich an einem heissen Tag abzukuehlen.",
    "gen176": "Nenne ein Wort, das Leute benutzen, wenn sie jemandes Namen nicht kennen.",
    "gen177": "Nenne etwas, das einen langen Roadtrip besser macht.",
    "gen178": "Nenne etwas, das man in einer Kramschublade findet.",
    "gen179": "Nenne etwas, das im Fernsehen immer einfacher aussieht.",
    "gen180": "Nenne etwas, woreuber Leute in sozialen Medien luegen.",
    "gen181": "Nenne etwas, auf das man barfuss ungern tritt.",
    "gen182": "Nenne einen Beruf, bei dem man eine Uniform traegt.",
    "gen183": "Nenne etwas, das man auf einem Flohmarkt findet.",
    "gen184": "Nenne etwas, das bei jedem Familientreffen passiert.",
    "gen185": "Nenne ein Gemuese, das Leute tatsaechlich gerne essen.",
    "gen186": "Nenne etwas, das Leute vor dem Verlassen des Hauses ueberpruefen.",
    "gen187": "Nenne ein beruehmtes fiktives Paar.",
    "gen188": "Nenne etwas, das immer in der Minibar eines Hotels ist.",
    "gen189": "Nenne etwas, das man in einem Schulspind findet.",
    "gen190": "Nenne etwas, das ein schlechtes Geburtstagsgeschenk waere.",
    "gen191": "Nenne ein Tier, von dem Leute ueberrascht sind, dass man es als Haustier halten kann.",
    "gen192": "Nenne etwas, das ein Lehrer jeden Tag sagt.",
    "gen193": "Nenne etwas, das ein Viertel sicher wirken laesst.",
    "gen194": "Nenne etwas, das man auf einem Jahrmarkt sieht.",
    "gen195": "Nenne eine Hausarbeit, die Kinder zu vermeiden versuchen.",
    "gen196": "Nenne etwas, das Leute direkt nach dem Training machen.",
    "gen197": "Nenne etwas, das gelb ist.",
    "gen198": "Nenne etwas, von dem Leute wuenschen, sie haetten frueher damit angefangen.",
    "gen199": "Nenne etwas, das Leute beim Campen immer vergessen.",
    "gen200": "Nenne etwas, das Leute um Mitternacht an Silvester machen.",
}
