# Spanish answer text translations for gen201-gen300 (ASCII-safe, same order as English)
ES_ANSWER_TEXTS_NEW2 = {
    "gen201": ["Beyonce", "Oprah", "Madonna", "Adele", "Rihanna", "Cher"],
    "gen202": ["Mirar su telefono", "Mirar los numeros del piso", "Quedarse en silencio", "Hacer charla trivial", "Mirar al suelo", "Presionar el boton de cerrar"],
    "gen203": ["Tomate", "Aguacate", "Pimiento", "Pepino", "Maiz", "Calabaza"],
    "gen204": ["Condimentos", "Sobras", "Cosas vencidas", "Queso", "Bicarbonato de sodio", "Pepinillos"],
    "gen205": ["Malabares", "Resolver un Rubik's Cube", "Trucos de cartas", "Girar un boligrafo", "Silbar con los dedos", "Moonwalking"],
    "gen206": ["Has crecido mucho", "En mis tiempos", "Estas comiendo suficiente", "Te quiero", "Tienes novio o novia", "No le digas a tus padres"],
    "gen207": ["Literally", "Ironic", "Irregardless", "Could care less", "Nauseous", "Peruse"],
    "gen208": ["Charla trivial", "Ejercicio", "Reuniones de trabajo", "Los hijos de otros", "Vino", "Eventos de networking"],
    "gen209": ["Serpiente", "Arana", "Oso", "Rata", "Murcielago", "Escorpion"],
    "gen210": ["Llaves", "Telefono", "Cartera", "Control remoto", "Calcetines", "Lentes"],
    "gen211": ["Titanic", "The Notebook", "Twilight", "Mean Girls", "High School Musical", "Frozen"],
    "gen212": ["Ropa", "Envolturas de comida", "Zapatos", "Platos o vasos", "Libros de texto", "Cargador de telefono"],
    "gen213": ["Papel higienico", "Condones", "Productos femeninos", "Crema para hemorroides", "Medicina antidiarreica", "Panales para adultos"],
    "gen214": ["Entrenador personal", "Bombero", "Atleta", "Militar", "Salvavidas", "Bailarin"],
    "gen215": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "Baby Shark", "Twinkle Twinkle Little Star"],
    "gen216": ["Italia", "Japon", "Francia", "Australia", "Grecia", "Islandia"],
    "gen217": ["Navegar redes sociales", "Ver television", "Comer bocadillos", "Limpiar", "Tomar una siesta", "Compras en linea"],
    "gen218": ["Galletas recien horneadas", "Play-Doh", "Protector solar", "Crayones", "Cesped recien cortado", "Casa de la abuela"],
    "gen219": ["Esperar en la fila", "Que llamen tu numero", "Papeleo", "Que te tomen la foto", "Examen de la vista", "Todo"],
    "gen220": ["Golf", "Natacion", "Gimnasia", "Patinaje sobre hielo", "Boliche", "Tiro con arco"],
    "gen221": ["Edad", "Estatura", "Fotos", "Trabajo", "Peso", "Pasatiempos"],
    "gen222": ["Dame de comer", "Te quiero", "Vamos a caminar", "Acariciame", "Quien esta en la puerta", "A donde fuiste"],
    "gen223": ["Dia de salud mental", "Buen clima afuera", "Resaca", "Entrevista de trabajo", "Evento familiar", "No quiso levantarse de la cama"],
    "gen224": ["Costillas", "Tacos", "Espagueti", "Alitas", "Elote", "Sandia"],
    "gen225": ["Carro", "Telefono", "Aire acondicionado", "Internet", "Lavadora", "Inodoro"],
    "gen226": ["Doctor", "Bombero", "Astronauta", "Veterinario", "Oficial de policia", "YouTuber"],
    "gen227": ["Navidad", "Halloween", "Accion de Gracias", "Pascua", "Dia de San Valentin", "Cuatro de Julio"],
    "gen228": ["Galletas", "Pan", "Salsa de pasta", "Pastel", "Sopa", "Guacamole"],
    "gen229": ["Bolsas de plastico", "Ropa", "Envases de comida para llevar", "Cargadores y cables", "Revistas", "Ligas"],
    "gen230": ["Tono del iPhone", "Pitido del microondas", "Toque de puerta", "Claxon de carro", "Alarma de despertador", "Sonido de Law & Order"],
    "gen231": ["Google", "YouTube", "Facebook", "Amazon", "Wikipedia", "Netflix"],
    "gen232": ["Trafico", "No sono la alarma", "Problemas con el carro", "Ninos", "No encontro estacionamiento", "Se perdio"],
    "gen233": ["Peluqueria", "Ascensor", "Dentista", "Uber o Lyft", "Reuniones familiares", "Sala de espera"],
    "gen234": ["Politica", "El ultimo pedazo de pastel", "Control remoto de la tele", "Quien cocino mejor", "Carne oscura vs carne blanca", "Distribucion de asientos"],
    "gen235": ["Costo", "Miedo a malas noticias", "Agujas", "Muy ocupado", "Odian esperar", "Verguenza"],
    "gen236": ["Brocoli", "Coles de Bruselas", "Espinacas", "Guisantes", "Esparragos", "Coliflor"],
    "gen237": ["Hacer un berrinche", "Hurgarse la nariz", "Correr desnudo", "Hablar con extranos", "Tener un amigo imaginario", "Dormir siesta en cualquier lugar"],
    "gen238": ["Pilas", "Boligrafos y lapices", "Ligas", "Cinta adhesiva", "Destornillador", "Menus de comida a domicilio"],
    "gen239": ["TikTok", "Instagram", "Facebook", "YouTube", "Twitter", "Candy Crush"],
    "gen240": ["Ir al gimnasio", "Comer mas sano", "Ahorrar dinero", "Dejar de fumar", "Leer mas libros", "Aprender un nuevo idioma"],
    "gen241": ["Musica", "Bocadillos", "Buena compania", "Paisajes bonitos", "Parar en atracciones curiosas", "Juegos en el carro"],
    "gen242": ["Servicios de salud", "Matricula universitaria", "Vivienda", "Palomitas del cine", "Gasolina", "Tinta de impresora"],
    "gen243": ["Serpiente", "Mono", "Tigre", "Caiman", "Tarantula", "Huron"],
    "gen244": ["Criptomonedas", "Vino", "Arte moderno", "La bolsa de valores", "Motores de carros", "Politica"],
    "gen245": ["Pastel", "Globos", "Regalos", "Velas", "Cantar Feliz Cumpleanos", "Gorros de fiesta"],
    "gen246": ["Lluvia", "Tormenta electrica", "Calor extremo", "Nieve", "Viento fuerte", "Granizo"],
    "gen247": ["Un aumento", "Tiempo libre", "Trabajar desde casa", "Que explique algo de nuevo", "Sobre un ascenso", "Si puede irse temprano"],
    "gen248": ["Chocolate", "Vainilla", "Fresa", "Masa de galleta", "Menta con chispas de chocolate", "Caramelo"],
    "gen249": ["Cepillarse los dientes", "Revisar el telefono", "Ir al bano", "Poner la alarma", "Leer un libro", "Cerrar las puertas con llave"],
    "gen250": ["Monopoly", "Uno", "Risk", "Scrabble", "Sorry", "Clue"],
    "gen251": ["Vacaciones", "Relaciones", "Comida", "Ejercicio", "Carro nuevo", "Hijos"],
    "gen252": ["Camion de helados", "Campana de la escuela", "Cancion de caricaturas", "Mama llamandote por tu nombre", "Sonidos de videojuegos", "Cancion de saltar la cuerda"],
    "gen253": ["Oficial de policia", "Espia", "Abogado", "Hacker", "Doctor", "Arqueologo"],
    "gen254": ["Helado", "Siestas", "Caricaturas", "Columpios", "Pastel de cumpleanos", "Plastico de burbujas"],
    "gen255": ["Papas fritas y helado", "Crema de cacahuate y pepinillos", "Pizza y aderezo ranch", "Chocolate y tocino", "Salsa picante y fruta", "Queso y miel"],
    "gen256": ["Morderse las unas", "Sudar", "Caminar de un lado a otro", "Inquietarse", "Hablar rapido", "Reirse nerviosamente"],
    "gen257": ["Television", "Ropa", "Juguetes", "Electronicos", "Electrodomesticos de cocina", "Toallas"],
    "gen258": ["Llaves", "Telefono", "Cartera", "Control remoto", "Calcetines", "Lentes de sol"],
    "gen259": ["Dia de salud mental", "Entrevista de trabajo", "Buen clima", "Resaca", "Evento deportivo", "Nuevo videojuego"],
    "gen260": ["Plato de dulces", "Tapetes de encaje", "Fotos viejas", "Muebles cubiertos de plastico", "Materiales de tejido", "Imanes en el refrigerador"],
    "gen261": ["Morgan Freeman", "Arnold Schwarzenegger", "Christopher Walken", "Donald Trump", "Matthew McConaughey", "Elvis Presley"],
    "gen262": ["Navegar redes sociales", "Enviar mensajes", "Jugar juegos", "Revisar correo", "Compras en linea", "Ver videos"],
    "gen263": ["Oso", "Leon", "Tiburon", "Elefante", "Cocodrilo", "Zorrillo"],
    "gen264": ["Dieta", "Ejercicio", "Levantarse temprano", "Dejar de fumar", "Ahorrar dinero", "Leer mas"],
    "gen265": ["Biblioteca", "Iglesia", "Hospital", "Sala de cine", "Funeral", "Sala de tribunal"],
    "gen266": ["Papas fritas", "Pizza", "Alitas", "Pastel", "Queso y galletas", "Mini hot dogs"],
    "gen267": ["Vino", "Carros", "Politica", "Tecnologia", "Arte", "Musica clasica"],
    "gen268": ["Palomitas", "Espinacas", "Elote", "Carne", "Caramelo", "Semillas de sesamo"],
    "gen269": ["The Lion King", "Titanic", "Star Wars", "Home Alone", "Wizard of Oz", "Forrest Gump"],
    "gen270": ["Autopista", "En medio de la nada", "Barrio peligroso", "Puente", "Tormenta de lluvia", "En una cita"],
    "gen271": ["Velas", "Cafe", "Perfume", "Jabon", "Extracto de vainilla", "Flores"],
    "gen272": ["Munecas", "Tapas de botellas", "Cucharas", "Recortes de unas", "Juguetes de comida rapida", "Rocas"],
    "gen273": ["Cargador de telefono", "Cepillo de dientes", "Ropa interior", "Desodorante", "Medicamentos", "Protector solar"],
    "gen274": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "ABC", "Jingle Bells"],
    "gen275": ["Cocinar", "Golf", "Estacionarse en paralelo", "Patinaje sobre hielo", "Malabares", "Hula hoop"],
    "gen276": ["Trafico", "No sono la alarma", "No encontro estacionamiento", "Se perdio", "Ninos", "Problemas con el carro"],
    "gen277": ["Pilas", "Ligas", "Boligrafos", "Cinta adhesiva", "Menus viejos", "Destornillador"],
    "gen278": ["Natacion", "Tenis", "Futbol", "Golf", "Gimnasia", "Remo"],
    "gen279": ["Gramatica", "Crianza de hijos", "Opciones de comida", "Moda", "Forma de manejar", "Gusto musical"],
    "gen280": ["Mirar la computadora", "Cargar un portapapeles", "Caminar rapido", "Hablar por telefono", "Mover papeles", "Enviar correos"],
    "gen281": ["Ladrido de perro", "Maullido de gato", "Mugido de vaca", "Cuac de pato", "Canto de gallo", "Siseo de serpiente"],
    "gen282": ["Visita a la oficina de vehiculos", "Cita con el doctor", "Compras en el supermercado", "Seguridad del aeropuerto", "Actualizaciones de software", "Armar muebles"],
    "gen283": ["Accion de Gracias", "Dia de San Valentin", "Navidad", "Nochevieja", "Dia de las Madres", "Dia de los Inocentes"],
    "gen284": ["Bano", "Tienda para adultos", "Consultorio medico", "Terapeuta", "Casa de empeno", "Fianzas"],
    "gen285": ["Carro", "Telefono", "Inodoro", "Aire acondicionado", "Computadora", "Cierre"],
    "gen286": ["Definitely", "Necessary", "Restaurant", "Accommodate", "Occurrence", "Wednesday"],
    "gen287": ["Musica", "Bocadillos", "Buena compania", "Juegos en el carro", "Ruta panoramica", "Audiolibros"],
    "gen288": ["Ropa sucia", "Telefono", "Posters", "Videojuegos", "Envases de comida vacios", "Audifonos"],
    "gen289": ["Santa Claus es real", "Comer verduras te hace fuerte", "El perro se fue a una granja", "El camion de helados no tiene", "Esto no va a doler", "Si cruzas los ojos se quedan asi"],
    "gen290": ["Galletas", "Pan", "Salsa de pasta", "Pastel", "Sopa", "Limonada"],
    "gen291": ["Papel higienico", "Bolsas de plastico", "Ropa", "Libros", "Envases de comida para llevar", "Cupones"],
    "gen292": ["Chinches de cama", "Cabello", "Camara oculta", "Manchas", "Moho", "Otra persona"],
    "gen293": ["Tocar guitarra", "Bailar", "Trucos de cartas", "Cantar", "Cocinar", "Malabares"],
    "gen294": ["Cantar", "Pensar", "Llorar", "Discutir con uno mismo", "Cepillarse los dientes", "Orinar"],
    "gen295": ["Monopoly", "Uno", "Mario Kart", "Risk", "Settlers of Catan", "Pictionary"],
    "gen296": ["Charla trivial", "Ensaladas", "Vino", "Hacer ejercicio", "Levantarse temprano", "Musica clasica"],
    "gen297": ["Bombero", "Militar", "Oficial de policia", "Piloto", "Doctor", "Astronauta"],
    "gen298": ["Hamburguesa", "Bistec", "Papas fritas", "Pasta", "Desayuno", "Ensalada"],
    "gen299": ["Impuestos", "Administrar dinero", "Cocinar", "Reparaciones del hogar", "Habilidades de comunicacion", "Primeros auxilios"],
    "gen300": ["Comida", "Un abrazo", "Musica", "Siesta", "Mascota", "Un cumplido"],
}
