ES_ANSWER_TEXTS_NEW1 = {
    "gen101": ["Papas Fritas", "Apio", "Manzanas", "Zanahorias", "Cereal", "Sopa"],
    "gen102": ["Vino", "Politica", "Arte", "Musica Clasica", "Finanzas", "Cocina Extranjera"],
    "gen103": ["Titanic", "The Notebook", "Bambi", "Up", "Marley & Me", "The Lion King"],
    "gen104": ["Cafe", "Velas", "Extracto de Vainilla", "Perfume", "Jabon", "Cacao en Polvo"],
    "gen105": ["No Aprender el Idioma", "Dar Propina Mal", "Comer en Trampas de Turistas", "Usar Ropa Inadecuada", "No Respetar las Costumbres", "Empacar de Mas"],
    "gen106": ["Oso", "Hipopotamo", "Koala", "Mapache", "Pez Globo", "Chimpance"],
    "gen107": ["Llaves", "Control Remoto", "Telefono", "Lentes", "Calcetines", "Cartera"],
    "gen108": ["Doctor", "Astronauta", "Bombero", "Atleta", "Veterinario", "Maestro"],
    "gen109": ["Ver Television", "Navegar Redes Sociales", "Comer Bocadillos", "Limpiar", "Siesta", "Sonar Despierto"],
    "gen110": ["Necessary", "Restaurant", "Wednesday", "Definitely", "Separate", "Receive"],
    "gen111": ["Cepillo de Dientes", "Cargador de Telefono", "Ropa Interior", "Calcetines", "Protector Solar", "Medicamentos"],
    "gen112": ["Plato de Dulces", "Tapetes de Encaje", "Fotos Viejas", "Plastico en los Muebles", "Articulos Religiosos", "Popurri"],
    "gen113": ["Tengo que Trabajar Temprano", "No me Siento Bien", "La Ninera", "Mi Mascota me Necesita", "Cita Temprano", "Trafico"],
    "gen114": ["Musica", "Direcciones", "Temperatura", "Donde Comer", "Paradas al Bano", "Velocidad al Manejar"],
    "gen115": ["Golf", "Boliche", "Pesca", "Cricket", "Dardos", "Badminton"],
    "gen116": ["Edad", "Trabajo", "Pasatiempos", "Historial Amoroso", "Estatura", "Lo que Comen"],
    "gen117": ["Esperar en la Recepcion", "Llenar Formularios", "Esperar en la Sala de Examen", "Tramites del Seguro", "Resultados de Laboratorio", "Conseguir una Referencia"],
    "gen118": ["Platos", "Lavanderia", "Limpiar el Bano", "Aspirar", "Trapear", "Planchar"],
    "gen119": ["Perro Ladrando", "Truenos", "Bebe Llorando", "Alarma de Carro", "Sirenas", "Crujidos"],
    "gen120": ["Presionar Botones", "Pedir Ayuda", "Entrar en Panico", "Revisar el Telefono", "Hablar con Otros", "Rezar"],
    "gen121": ["Sherlock Holmes", "Scooby-Doo", "Batman", "Nancy Drew", "Inspector Clouseau", "Columbo"],
    "gen122": ["Oficina de Tramites", "Atracciones del Parque", "Seguridad del Aeropuerto", "Cafeteria", "Caja del Supermercado", "Bano Publico"],
    "gen123": ["Pilas", "Ligas", "Boligrafos", "Cinta Adhesiva", "Menus de Comida a Domicilio", "Llaves Viejas"],
    "gen124": ["Happy Birthday", "Bohemian Rhapsody", "Don't Stop Believin'", "Sweet Caroline", "Twinkle Twinkle Little Star", "ABC Song"],
    "gen125": ["Hacer Ejercicio", "Comer mas Sano", "Ahorrar Dinero", "Leer mas", "Aprender un Idioma", "Levantarse Temprano"],
    "gen126": ["Brocoli", "Coles de Bruselas", "Espinacas", "Esparragos", "Guisantes", "Coliflor"],
    "gen127": ["Telefono", "Llaves", "Cartera", "Cabello", "Estufa", "Cerrar con Llave"],
    "gen128": ["Torre Eiffel", "Estatua de la Libertad", "Torre Inclinada de Pisa", "Big Ben", "Gran Muralla China", "Coliseo"],
    "gen129": ["Cantar", "Subir el Volumen", "Bailar", "Decir 'Esta es mi Cancion'", "Guitarra Imaginaria", "Cerrar los Ojos"],
    "gen130": ["123456", "Password", "Su Cumpleanos", "Nombre de su Mascota", "Qwerty", "abc123"],
    "gen131": ["Ardilla", "Pajaro", "Conejo", "Venado", "Mapache", "Zarigueya"],
    "gen132": ["Audifonos", "Luces de Navidad", "Cabello", "Hilo de Pesca", "Collares", "Cables de Extension"],
    "gen133": ["La Cuenta", "Mas Pan", "Otra Mesa", "Sustituciones", "Caja para Sobras", "El Gerente"],
    "gen134": ["Dia de Accion de Gracias", "Navidad", "Pascua", "Cuatro de Julio", "Hanukkah", "Domingo de Super Bowl"],
    "gen135": ["Agua", "Comida", "Estacionamiento", "Recuerdos", "Wi-Fi", "Revistas"],
    "gen136": ["Sentirse Enfermo", "Muy Cansado", "Trabajo", "Mal Clima", "Emergencia Familiar", "Simplemente no Quiere Ir"],
    "gen137": ["Estampillas", "Monedas", "Figuras de Accion", "Tarjetas de Beisbol", "Discos de Vinilo", "Conchas de Mar"],
    "gen138": ["Biblioteca", "Iglesia", "Sala de Cine", "Hospital", "Cuarto del Bebe", "Funeral"],
    "gen139": ["Cornhole", "Herradura", "Voleibol", "Frisbee", "Juegos de Cartas", "Badminton"],
    "gen140": ["Usar el Telefono", "Recoger Monedas", "Atar Zapatos", "Abotonar una Camisa", "Escribir", "Abrir un Frasco"],
    "gen141": ["Hogwarts", "Narnia", "Wakanda", "Middle-earth", "Neverland", "La Fabrica de Willy Wonka"],
    "gen142": ["Dulces", "Refresco", "Papas Fritas", "Sandwiches", "Comida Rapida", "Una Petaca"],
    "gen143": ["Carro", "Telefono", "Inodoro", "Aire Acondicionado", "Lavadora", "Internet"],
    "gen144": ["Limon", "Lima", "Naranja", "Fresa", "Pina", "Cereza"],
    "gen145": ["Ver el Telefono", "Hablar", "Comer Pan", "Tomar", "Ver a la Gente", "Leer el Menu de Nuevo"],
    "gen146": ["Friends", "The Office", "Breaking Bad", "Stranger Things", "Game of Thrones", "Grey's Anatomy"],
    "gen147": ["Manzana", "Trabajos por Calificar", "Taza de Cafe", "Boligrafos", "Engrapadora", "Placa con Nombre"],
    "gen148": ["Queso Azul", "Durian", "Pescado", "Huevos Duros", "Kimchi", "Coles de Bruselas"],
    "gen149": ["Comer", "Navegar Redes Sociales", "Dar un Paseo", "Siesta", "Hacer Mandados", "Chismear"],
    "gen150": ["Monopoly", "Risk", "Scrabble", "Uno", "Sorry!", "Trivial Pursuit"],
    "gen151": ["Vaso de Agua", "Telefono", "Boligrafo", "Florero", "Llaves", "Control Remoto"],
    "gen152": ["Bebe Llorando", "Alarma", "Unas en un Pizarron", "Ronquidos", "Perro Ladrando", "Telefono Sonando"],
    "gen153": ["Ver el Telefono", "Hablar entre Ellos", "Tomar", "Comer Pan", "Ver la Comida de Otros", "Leer el Menu de Nuevo"],
    "gen154": ["Ropa Nueva", "Vacaciones", "Con Amigos", "Redes Sociales", "Evento o Momento Especial", "Aburrido"],
    "gen155": ["Papel Higienico", "Bateria del Telefono", "Gasolina", "Dinero", "Agua Caliente", "Leche"],
    "gen156": ["Panqueques", "Bistec", "Huevos", "Sandwich", "Pasta", "Queso a la Plancha"],
    "gen157": ["Inodoro", "Espejo", "Lavabo", "Jabon", "Toalla", "Papel Higienico"],
    "gen158": ["La Biblia", "Terminos y Condiciones", "Novelas Clasicas", "Shakespeare", "Correos del Trabajo", "Articulos de Noticias"],
    "gen159": ["Cocinar", "Manejar", "Cantar", "Bailar", "Hacer Varias Cosas a la Vez", "Contar Chistes"],
    "gen160": ["Biblioteca", "Iglesia", "Hospital", "Sala de Cine", "Funeral", "Tribunal"],
    "gen161": ["Vela", "Jabon", "Perfume", "Flores", "Crema", "Champu"],
    "gen162": ["Television", "Laptop", "Telefono", "Consola de Videojuegos", "Juguetes", "Ropa"],
    "gen163": ["Trafico", "Se Quedo Dormido", "Ninos", "Problemas con el Carro", "Clima", "No Encontro Estacionamiento"],
    "gen164": ["Hacer Parrillada", "Chistes de Papa", "Siestas", "Termostato", "Deportes", "Cuidar el Cesped"],
    "gen165": ["Papas Fritas", "Apio", "Manzana", "Cereal", "Sopa", "Palomitas"],
    "gen166": ["Dulces", "Bebidas", "Comida Rapida", "Papas Fritas", "Alcohol", "Telefono"],
    "gen167": ["Llaves", "Control Remoto", "Telefono", "Lentes", "Calcetines", "Ligas para el Cabello"],
    "gen168": ["Arana", "Hormiga", "Rata", "Serpiente", "Escorpion", "Gato"],
    "gen169": ["Helado", "Chocolate", "Pizza", "Papas Fritas", "Comida Rapida", "Galletas"],
    "gen170": ["Comida No Lista", "Casa Desordenada", "No Suficiente Comida", "Que los Invitados se Lleven Bien", "Arreglo de Asientos", "Que se Acaben las Bebidas"],
    "gen171": ["Romance", "Drama", "Guerra", "Animada", "Historia Real", "Deportes"],
    "gen172": ["Hacer un Muneco de Nieve", "Dormir Hasta Tarde", "Ver Peliculas", "Pelea de Bolas de Nieve", "Tomar Chocolate Caliente", "Trineo"],
    "gen173": ["Salud", "Vivienda", "Universidad", "Gasolina", "Comida", "Planes de Telefono"],
    "gen174": ["Susto", "Vio un Insecto", "Dolor", "Emocion", "Enojo", "Montana Rusa"],
    "gen175": ["Ir a Nadar", "Comer Helado", "Prender el Aire Acondicionado", "Tomar Agua Fria", "Sentarse en la Sombra", "Usar un Ventilador"],
    "gen176": ["Amigo", "Compadre", "Hombre", "Senor o Senora", "Oye Tu", "Tipo"],
    "gen177": ["Musica", "Bocadillos", "Buena Compania", "Podcasts", "Ruta Escenica", "Paradas Frecuentes"],
    "gen178": ["Pilas", "Cinta Adhesiva", "Boligrafos", "Ligas", "Llaves Viejas", "Menus de Comida a Domicilio"],
    "gen179": ["Cocinar", "Pelear", "Renovar la Casa", "Bailar", "Huir del Peligro", "Estacionarse en Paralelo"],
    "gen180": ["Que tan Felices Son", "Su Apariencia", "Estado Sentimental", "Ingresos o Riqueza", "Lo que Comen", "Su Edad"],
    "gen181": ["Lego", "Vidrio", "Tachuela", "Caca de Perro", "Insecto", "Chicle"],
    "gen182": ["Policia", "Bombero", "Doctor o Enfermera", "Militar", "Trabajador de Comida Rapida", "Piloto"],
    "gen183": ["Ropa Vieja", "Libros", "Muebles", "Juguetes", "Cosas de Cocina", "Electronicos"],
    "gen184": ["Alguien Pregunta Cuando te Casas", "Comer de Mas", "Discusiones", "Tomar Fotos", "Chismes", "Ninos Corriendo por Todos Lados"],
    "gen185": ["Maiz", "Papas", "Zanahorias", "Ejotes", "Brocoli", "Guisantes"],
    "gen186": ["Telefono", "Llaves", "Cartera", "Cabello y Apariencia", "Puerta con Llave", "Clima"],
    "gen187": ["Romeo y Julieta", "Mickey y Minnie", "Barbie y Ken", "Shrek y Fiona", "La Bella y la Bestia", "Jack y Rose"],
    "gen188": ["Agua", "Refresco", "Alcohol", "Chocolate", "Nueces", "Papas Fritas"],
    "gen189": ["Libros de Texto", "Mochila", "Comida Vieja", "Chaqueta", "Espejo", "Ropa de Gimnasia"],
    "gen190": ["Calcetines", "Productos de Limpieza", "Libro de Dieta", "Tarjeta de Regalo con Poco Dinero", "Desodorante", "Una Plancha"],
    "gen191": ["Serpiente", "Erizo", "Cerdo", "Mono", "Tarantula", "Sugar Glider"],
    "gen192": ["Silencio", "Abran sus Libros", "Pongan Atencion", "La Tarea es para Hoy", "Buenos Dias", "Nada de Telefonos"],
    "gen193": ["Alumbrado Publico", "Vecinos Amigables", "Presencia Policial", "Calles Limpias", "Bajo Crimen", "Camaras de Seguridad"],
    "gen194": ["Rueda de la Fortuna", "Algodon de Azucar", "Juegos", "Montana Rusa", "Payasos", "Peluches"],
    "gen195": ["Platos", "Limpiar su Cuarto", "Sacar la Basura", "Aspirar", "Cortar el Cesped", "Lavanderia"],
    "gen196": ["Tomar Agua", "Banarse", "Comer", "Estirar", "Verse en el Espejo", "Desplomarse"],
    "gen197": ["Platano", "Sol", "Autobus Escolar", "Pato de Hule", "Limon", "Taxi"],
    "gen198": ["Ahorrar Dinero", "Hacer Ejercicio", "Comer Saludable", "Aprender un Idioma", "Viajar", "Leer"],
    "gen199": ["Repelente de Insectos", "Papel Higienico", "Linterna", "Cerillos o Encendedor", "Almohada", "Abrelatas"],
    "gen200": ["Besar a Alguien", "Contar Hacia Atras", "Brindar con Champana", "Ver Fuegos Artificiales", "Gritar Feliz Ano Nuevo", "Pedir un Deseo"],
}
