# Spanish answer text translations (same order as English answers)
ES_ANSWER_TEXTS = {
    "q001": ["Toalla", "Protector Solar", "Sombrilla", "Nevera Portatil", "Silla", "Gafas de Sol"],
    "q002": ["Resfriado o Gripe", "Dolor de Cabeza", "Dolor de Estomago", "Dia de Salud Mental", "Dolor de Espalda", "Cita con el Dentista"],
    "q003": ["Tarjeta de Credito", "Efectivo", "Identificacion", "Fotos", "Recibos", "Tarjetas de Presentacion"],
    "q004": ["Redes Sociales", "Mensajes", "Jugar Juegos", "Ver Videos", "Revisar Correo", "Leer Noticias"],
    "q005": ["Pepperoni", "Champinones", "Salchicha", "Cebollas", "Pimientos", "Aceitunas"],
    "q006": ["Cepillo de Dientes", "Cargador de Telefono", "Ropa Interior", "Medicamentos", "Desodorante", "Pijamas"],
    "q007": ["Aranas", "Alturas", "Serpientes", "Hablar en Publico", "La Oscuridad", "Volar"],
    "q008": ["Cepillarse los Dientes", "Revisar el Telefono", "Ver Television", "Leer", "Ducharse", "Poner la Alarma"],
    "q009": ["Hacer mas Ejercicio", "Perder Peso", "Ahorrar Dinero", "Dejar de Fumar", "Leer mas", "Viajar mas"],
    "q010": ["Escritorio", "Pizarra", "Silla", "Libros", "Computadora", "Reloj"],
    "q011": ["Futbol Americano", "Basquetbol", "Beisbol", "Tenis", "Hockey", "Golf"],
    "q012": ["Ketchup", "Queso", "Lechuga", "Tomate", "Cebolla", "Pepinillos"],
    "q013": ["Cama", "Television", "Biblia", "Toallas", "Minibar", "Caja Fuerte"],
    "q014": ["Tiburon", "Delfin", "Ballena", "Pulpo", "Tortuga Marina", "Medusa"],
    "q015": ["Estampillas", "Monedas", "Tarjetas", "Arte", "Discos de Vinilo", "Zapatos"],
    "q016": ["Trafico", "Se Quedo Dormido", "Ninos", "Problemas con el Carro", "Mal Clima", "Llaves Perdidas"],
    "q017": ["Huevos", "Tostadas", "Cereal", "Panqueques", "Tocino", "Fruta"],
    "q018": ["Vamos Equipo", "El Arbitro esta Ciego", "Gol", "Abucheo", "Defensa", "MVP"],
    "q019": ["Bailar", "Beber", "Hablar con la Gente", "Comer", "Jugar Juegos", "Tomar Fotos"],
    "q020": ["Gafas de Sol", "Cargador de Telefono", "Botella de Agua", "Llanta de Repuesto", "Registro del Auto", "Paraguas"],
    "q021": ["Chequeo", "Resfriado o Gripe", "Dolor", "Receta Medica", "Lesion", "Vacunacion"],
    "gen001": ["Leche", "Pan", "Huevos", "Mantequilla", "Fruta", "Papel Higienico"],
    "gen002": ["Ver Television", "Navegar el Telefono", "Dormir", "Comer", "Limpiar", "Jugar Videojuegos"],
    "gen003": ["Brocoli", "Coles de Bruselas", "Espinacas", "Guisantes", "Coliflor", "Esparragos"],
    "gen004": ["The Lion King", "Titanic", "Harry Potter", "Star Wars", "Shrek", "Frozen"],
    "gen005": ["Charla Trivial", "La Comida", "Los Chistes del Jefe", "Juegos de Equipo", "Bailar", "Estar Ahi"],
    "gen006": ["Italia", "Japon", "Francia", "Grecia", "Australia", "Maldivas"],
    "gen007": ["Soplar las Velas", "Comer Pastel", "Abrir Regalos", "Hacer una Fiesta", "Pedir un Deseo", "Cantar Feliz Cumpleanos"],
    "gen008": ["Telefono", "Carro", "WiFi", "Lavadora", "Inodoro", "Aire Acondicionado"],
    "gen009": ["Golf", "Natacion", "Gimnasia", "Boliche", "Patinaje sobre Hielo", "Tiro con Arco"],
    "gen010": ["Oso", "Zorrillo", "Mono", "Elefante", "Loro", "Cabra"],
    "gen011": ["Definitely", "Restaurant", "Necessary", "Separate", "Embarrassed", "Wednesday"],
    "gen012": ["Su Edad", "Su Trabajo", "Sus Pasatiempos", "Cuanto Beben", "Sus Relaciones Pasadas", "Su Estatura"],
    "gen013": ["Tenirse el Cabello", "Hacer Ejercicio", "Maquillarse", "Botox", "Vestirse mas Joven", "Cuidado de la Piel"],
    "gen014": ["Pajaros Cantando", "Lluvia", "Olas del Mar", "Viento", "Grillos", "Cascada"],
    "gen015": ["Pilas", "Boligrafos", "Ligas", "Llaves", "Cinta Adhesiva", "Menus de Comida a Domicilio"],
    "gen016": ["Costillas", "Espagueti", "Tacos", "Alitas", "Elote", "Burrito"],
    "gen017": ["Friends", "The Office", "Stranger Things", "Breaking Bad", "Grey's Anatomy", "Game of Thrones"],
    "gen018": ["Ver Television", "Navegar Redes Sociales", "Limpiar", "Comer", "Siesta", "Hablar con Amigos"],
    "gen019": ["Filas Largas", "Retrasos", "Asientos Estrechos", "Bebes Llorando", "Equipaje Perdido", "Turbulencia"],
    "gen020": ["Impuestos", "Tarea", "Empacar", "Compras Navidenas", "Lavanderia", "Limpieza"],
    "gen021": ["Cerveza", "Margarita", "Whiskey", "Vodka con Soda", "Vino", "Old Fashioned"],
    "gen022": ["Morgan Freeman", "Arnold Schwarzenegger", "Christopher Walken", "Donald Trump", "Matthew McConaughey", "Owen Wilson"],
    "gen023": ["Estres", "Telefono", "Ruido", "Cafe", "Dolor", "Pesadilla"],
    "gen024": ["Muy Cansado", "Sin Tiempo", "Muy Caro", "Mal Clima", "Lesion", "Mucha Pereza"],
    "gen025": ["Musica", "Direcciones", "Temperatura", "Donde Comer", "Quien Maneja", "Paradas al Bano"],
    "gen026": ["Platos", "Limpiar el Bano", "Lavanderia", "Aspirar", "Sacar la Basura", "Cortar el Cesped"],
    "gen027": ["Palomitas", "Dulces", "Nachos", "Hot Dog", "Refresco", "Helado"],
    "gen028": ["Telefono", "Notas", "Chicle", "Juguetes", "Gorro", "Audifonos"],
    "gen029": ["Hipopotamo", "Delfin", "Cisne", "Alce", "Koala", "Ornitorrinco"],
    "gen030": ["Perfume", "Cafe", "Velas", "Jabon", "Flores", "Extracto de Vainilla"],
    "gen031": ["Sherlock Holmes", "Batman", "Scooby-Doo", "Inspector Gadget", "Nancy Drew", "Hercule Poirot"],
    "gen032": ["El Olor", "Decoracion", "Limpieza", "La Cocina", "Mascotas", "Fotos"],
    "gen033": ["Cartas", "Charadas", "Monopoly", "Scrabble", "Trivia", "Pictionary"],
    "gen034": ["Sintomas de Salud", "Ellos Mismos", "Chismes de Famosos", "Como se Escribe una Palabra", "Su Ex", "Preguntas Tontas"],
    "gen035": ["Condones", "Papel Higienico", "Productos Femeninos", "Laxantes", "Panales para Adultos", "Crema para la Comezon"],
    "gen036": ["Torre Eiffel", "Estatua de la Libertad", "Gran Muralla China", "Big Ben", "Piramides", "Taj Mahal"],
    "gen037": ["Impuestos", "Criptomonedas", "Politica", "Motores de Autos", "Vino", "Bolsa de Valores"],
    "gen038": ["Hablar de tu Ex", "Estar en el Telefono", "Llegar Tarde", "Comer Comida Sucia", "Hablar de Matrimonio", "Eructar"],
    "gen039": ["Rosas", "Tulipanes", "Girasoles", "Lirios", "Orquideas", "Margaritas"],
    "gen040": ["Nuggets", "Alitas", "Varicela", "Sopa", "Dedos", "Pechuga"],
    "gen041": ["Perros Ladrando", "Construccion", "Cortadoras de Cesped", "Trafico", "Fiestas", "Ninos Jugando"],
    "gen042": ["Helado", "Chocolate", "Mac and Cheese", "Pizza", "Papas Fritas", "Sopa"],
    "gen043": ["Doctor", "Astronauta", "Bombero", "Policia", "Atleta", "Veterinario"],
    "gen044": ["Telefono", "Mascotas", "Fotos Familiares", "Cartera", "Documentos", "Laptop"],
    "gen045": ["Mango", "Sandia", "Granada", "Naranja", "Durazno", "Toronja"],
    "gen046": ["Grey's Anatomy", "House", "ER", "Scrubs", "The Good Doctor", "Chicago Med"],
    "gen047": ["Cerrar la Puerta", "Agarrar Llaves", "Apagar las Luces", "Agarrar el Telefono", "Apagar la Estufa", "Agarrar la Cartera"],
    "gen048": ["No lo Vi", "Telefono sin Bateria", "Estaba Ocupado", "Se me Olvido", "Me Quede Dormido", "Mala Senal"],
    "gen049": ["Golf", "Correr", "Natacion", "Tenis", "Boliche", "Ciclismo"],
    "gen050": ["Cerdo", "Cuervo", "Pulpo", "Perro", "Rata", "Elefante"],
    "gen051": ["Boligrafo", "Encendedor", "Paraguas", "Libros", "Cargador", "Tupperware"],
    "gen052": ["Como Hacer Impuestos", "Presupuesto", "Cocinar", "Primeros Auxilios", "Mantenimiento del Auto", "Como Votar"],
    "gen053": ["Biblioteca", "Iglesia", "Cine", "Hospital", "Funeral", "Salon de Clases"],
    "gen054": ["Pizza", "Lasana", "Comida China", "Chili", "Estofado", "Pavo de Accion de Gracias"],
    "gen055": ["Darth Vader", "Joker", "Thanos", "Voldemort", "Cruella de Vil", "Scar"],
    "gen056": ["Esperar en la Fila", "Papeleo", "Foto", "Examen de la Vista", "Examen Escrito", "Que te Llamen"],
    "gen057": ["Piano", "Guitarra", "Violin", "Bateria", "Saxofon", "Arpa"],
    "gen058": ["Escuchar Musica", "Tocar el Claxon", "Revisar el Telefono", "Cantar", "Maldecir", "Podcast"],
    "gen059": ["Que Comer", "Termostato", "Platos", "Control Remoto", "Tapa del Inodoro", "Ronquidos"],
    "gen060": ["Sofa", "Carro", "Lavanderia", "Recamara", "Aeropuerto", "Gimnasio"],
    "gen061": ["Lluvia", "Nieve", "Huracan", "Calor Extremo", "Tormenta Electrica", "Niebla"],
    "gen062": ["Dulces", "Tejido", "Fotos Viejas", "Tapetes de Encaje", "Vitrina de Porcelana", "Gatos"],
    "gen063": ["Persecucion de Autos", "Explosion", "Escena de Pelea", "Tiroteo", "Frase Ingeniosa", "El Heroe se Aleja"],
    "gen064": ["Membresia del Gimnasio", "Libros de Cocina", "Caminadora", "Libros", "Extractor de Jugos", "Plancha"],
    "gen065": ["Usa Hilo Dental", "Cepillate Dos Veces al Dia", "Usa Enjuague Bucal", "Reduce el Azucar", "Regresa en 6 Meses", "Cambia tu Cepillo de Dientes"],
    "gen066": ["Bohemian Rhapsody", "Happy Birthday", "Don't Stop Believin'", "Sweet Caroline", "Mr. Brightside", "Baby Shark"],
    "gen067": ["Comida", "Agua", "Cafe", "Recuerdos", "Estacionamiento", "WiFi"],
    "gen068": ["Monopoly", "Risk", "Uno", "Scrabble", "Sorry", "Settlers of Catan"],
    "gen069": ["Navegar en Internet", "Revisar el Telefono", "Platicar con Companeros", "Tomar un Descanso Largo", "Siesta", "Salir Temprano"],
    "gen070": ["Galletas", "Pan", "Salsa para Pasta", "Pay", "Sopa", "Limonada"],
    "gen071": ["Tocar Guitarra", "Trucos de Magia", "Bailar", "Hacer Malabares", "Cantar", "Preparar Bebidas"],
    "gen072": ["Telefono", "Ropa en el Piso", "Posters", "Consola de Videojuegos", "Audifonos", "Bolsas de Botanas Vacias"],
    "gen073": ["Helicoptero", "Lamborghini", "Globo Aerostatico", "Yate", "Jet Privado", "Submarino"],
    "gen074": ["Navidad", "Dia de San Valentin", "Accion de Gracias", "Black Friday", "Aniversario de Bodas", "Pascua"],
    "gen075": ["Fax", "VCR", "Reproductor de CD", "Biper", "Disquete", "Telefono de Tapa"],
    "gen076": ["Gimnasia", "Salto con Garrocha", "Clavados", "Patinaje Artistico", "Levantamiento de Pesas", "Esgrima"],
    "gen077": ["Perezoso", "Tortuga", "Caracol", "Koala", "Manati", "Estrella de Mar"],
    "gen078": ["Revisar el Telefono", "Ir al Bano", "Cepillarse los Dientes", "Hacer Cafe", "Estirarse", "Posponer la Alarma"],
    "gen079": ["Vaqueros", "BBQ", "Armas", "Camionetas Grandes", "Petroleo", "Bistecs"],
    "gen080": ["Cafetera", "Impresora", "Computadora", "Engrapadora", "Pizarra", "Reloj"],
    "gen081": ["Fantasmas", "Sonidos Escalofriantes", "Oscuridad", "Sustos Repentinos", "Aranas", "Payasos"],
    "gen082": ["Se Apaga", "Autocorrector", "Llamadas Spam", "Actualizaciones", "Notificaciones", "Se Congela"],
    "gen083": ["Basquetbol", "Futbol", "Futbol Americano", "Voleibol", "Hockey", "Remo"],
    "gen084": ["Tiburon", "Serpiente", "Murcielago", "Lobo", "Arana", "Hiena"],
    "gen085": ["Romper un Espejo", "Gato Negro", "Pasar Bajo una Escalera", "Numero 13", "Abrir Paraguas Adentro", "Derramar Sal"],
    "gen086": ["Imanes", "Postales", "Vasos de Shot", "Camisetas", "Llaveros", "Globos de Nieve"],
    "gen087": ["Investigar la Empresa", "Vestirse Bien", "Practicar Respuestas", "Ducharse", "Imprimir Curriculum", "Buscar Direcciones"],
    "gen088": ["Vino", "Queso", "Whiskey", "Jeans", "Sarten de Hierro", "Vinagre Balsamico"],
    "gen089": ["Alguien Llora", "Primer Baile", "Corte del Pastel", "Lanzamiento del Ramo", "Discursos", "Alguien se Emborracha"],
    "gen090": ["Roble", "Palmera", "Pino", "Arce", "Abedul", "Sauce"],
    "gen091": ["Work", "Sick", "Coming", "Town", "Made", "Land"],
    "gen092": ["Tienda de Campana", "Fogata", "Bolsa de Dormir", "Malvaviscos", "Repelente de Insectos", "Nevera Portatil"],
    "gen093": ["Pastel de Frutas", "Ponche de Huevo", "Salsa de Arandanos", "Camotes", "Relleno", "Pastel de Carne"],
    "gen094": ["123456", "Password", "Su Cumpleanos", "Nombre de su Mascota", "Qwerty", "Su Nombre"],
    "gen095": ["Burpees", "Correr", "Planchas", "Sentadillas", "Lagartijas", "Desplantes"],
    "gen096": ["Ardilla", "Pajaro", "Conejo", "Venado", "Mapache", "Gato"],
    "gen097": ["Birth", "To", "Holi", "Every", "Sun", "Pay"],
    "gen098": ["Revistas Viejas", "Sillas Incomodas", "Television", "Pecera", "Gel Antibacterial", "Ninos Llorando"],
    "gen099": ["Canguro", "Koala", "Sydney Opera House", "Cocodrilo", "Vegemite", "Gran Barrera de Coral"],
    "gen100": ["Incendio", "Accidente de Auto", "Robo", "Ataque al Corazon", "Pelea", "Persona Sospechosa"],
}
