ES_QUESTIONS_NEW1 = {
    "gen101": "Nombra un alimento que es imposible comer en silencio.",
    "gen102": "Nombra algo que la gente finge entender en una cena.",
    "gen103": "Nombra una pelicula que siempre hace llorar a la gente.",
    "gen104": "Nombra algo que huele mejor de lo que sabe.",
    "gen105": "Nombra algo que los turistas siempre hacen mal al visitar un nuevo pais.",
    "gen106": "Nombra un animal que parece tierno pero en realidad es peligroso.",
    "gen107": "Nombra algo que la gente siempre pierde en su propia casa.",
    "gen108": "Nombra un trabajo que los ninos dicen que quieren cuando sean grandes.",
    "gen109": "Nombra algo que la gente hace para procrastinar.",
    "gen110": "Nombra una palabra que la gente comunmente escribe mal.",
    "gen111": "Nombra algo que la gente siempre olvida empacar para un viaje.",
    "gen112": "Nombra algo que siempre hay en la casa de una abuela.",
    "gen113": "Nombra una excusa que la gente usa para irse temprano de una fiesta.",
    "gen114": "Nombra algo por lo que la gente discute en un viaje por carretera.",
    "gen115": "Nombra un deporte que es aburrido de ver pero divertido de jugar.",
    "gen116": "Nombra algo sobre lo que la gente miente en una primera cita.",
    "gen117": "Nombra algo que tarda una eternidad en el consultorio del doctor.",
    "gen118": "Nombra una tarea del hogar que todos odian hacer.",
    "gen119": "Nombra un sonido que te despierta en medio de la noche.",
    "gen120": "Nombra algo que la gente hace cuando esta atrapada en un ascensor.",
    "gen121": "Nombra un famoso detective ficticio.",
    "gen122": "Nombra algo que siempre tiene una fila larga.",
    "gen123": "Nombra algo que encontrarias en un cajon de cosas.",
    "gen124": "Nombra una cancion de la que todos saben la letra.",
    "gen125": "Nombra algo que la gente siempre dice que hara pero nunca hace.",
    "gen126": "Nombra una verdura que los ninos se niegan a comer.",
    "gen127": "Nombra algo que la gente revisa antes de salir de casa.",
    "gen128": "Nombra un monumento famoso frente al que la gente se toma fotos.",
    "gen129": "Nombra algo que la gente hace cuando suena una cancion que les encanta.",
    "gen130": "Nombra una contrasena comun que la gente usa.",
    "gen131": "Nombra un animal que podrias ver en el jardin de alguien.",
    "gen132": "Nombra algo que siempre se enreda.",
    "gen133": "Nombra algo que la gente tiene miedo de pedir en un restaurante.",
    "gen134": "Nombra un dia festivo que involucra mucha cocina.",
    "gen135": "Nombra algo que siempre es mas caro en el aeropuerto.",
    "gen136": "Nombra una razon por la que alguien cancelaria planes a ultimo momento.",
    "gen137": "Nombra algo que la gente colecciona.",
    "gen138": "Nombra un lugar donde tienes que susurrar.",
    "gen139": "Nombra un juego que la gente juega en una parrillada.",
    "gen140": "Nombra algo que es dificil hacer con guantes puestos.",
    "gen141": "Nombra un lugar ficticio que todos desearian que fuera real.",
    "gen142": "Nombra algo que la gente mete a escondidas al cine.",
    "gen143": "Nombra algo que siempre parece romperse en el peor momento.",
    "gen144": "Nombra una fruta que la gente pone en las bebidas.",
    "gen145": "Nombra algo que la gente hace mientras espera su comida en un restaurante.",
    "gen146": "Nombra una serie de television que la gente ve de un tiron.",
    "gen147": "Nombra algo que encontrarias en el escritorio de un maestro.",
    "gen148": "Nombra algo que huele terrible pero la gente come de todos modos.",
    "gen149": "Nombra algo que la gente hace en su hora de almuerzo en el trabajo.",
    "gen150": "Nombra un juego de mesa que causa peleas en la familia.",
    "gen151": "Nombra algo que un gato tira de la mesa.",
    "gen152": "Nombra un sonido que es dificil de ignorar.",
    "gen153": "Nombra algo que la gente hace mientras espera comida en un restaurante.",
    "gen154": "Nombra una razon por la que la gente se toma una selfie.",
    "gen155": "Nombra algo que siempre parece acabarse en el peor momento.",
    "gen156": "Nombra una comida que sabe mejor cuando la hace otra persona.",
    "gen157": "Nombra algo que encuentras en todos los banos.",
    "gen158": "Nombra algo que la gente finge haber leido.",
    "gen159": "Nombra algo en lo que la gente siempre dice ser buena pero usualmente no lo es.",
    "gen160": "Nombra un lugar donde tienes que estar callado.",
    "gen161": "Nombra algo que huele bien pero no deberias comer.",
    "gen162": "Nombra un articulo por el que la gente pelea en Black Friday.",
    "gen163": "Nombra una razon por la que la gente llega tarde al trabajo.",
    "gen164": "Nombra algo que a todos los papas parece encantarles.",
    "gen165": "Nombra un alimento que es imposible comer en silencio.",
    "gen166": "Nombra algo que la gente mete a escondidas al cine.",
    "gen167": "Nombra algo que la gente siempre pierde en su casa.",
    "gen168": "Nombra un animal que seria aterrador si fuera del tamano de un caballo.",
    "gen169": "Nombra una comida que la gente come cuando esta estresada.",
    "gen170": "Nombra algo que pone nerviosa a la gente cuando organiza una cena.",
    "gen171": "Nombra un genero de pelicula que hace llorar a la gente.",
    "gen172": "Nombra algo que la gente hace en un dia de nieve.",
    "gen173": "Nombra algo que es mucho mas caro de lo que deberia ser.",
    "gen174": "Nombra una razon por la que alguien gritaria.",
    "gen175": "Nombra algo que la gente hace para refrescarse en un dia caluroso.",
    "gen176": "Nombra una palabra que la gente usa cuando no sabe el nombre de alguien.",
    "gen177": "Nombra algo que hace mejor un viaje largo por carretera.",
    "gen178": "Nombra algo que encontrarias en un cajon de cosas.",
    "gen179": "Nombra algo que siempre parece mas facil en la television.",
    "gen180": "Nombra algo sobre lo que la gente miente en redes sociales.",
    "gen181": "Nombra algo que odiarias pisar descalzo.",
    "gen182": "Nombra un trabajo donde usas uniforme.",
    "gen183": "Nombra algo que encontrarias en una venta de garage.",
    "gen184": "Nombra algo que pasa en cada reunion familiar.",
    "gen185": "Nombra una verdura que la gente realmente disfruta comer.",
    "gen186": "Nombra algo que la gente revisa antes de salir de casa.",
    "gen187": "Nombra una pareja ficticia famosa.",
    "gen188": "Nombra algo que siempre esta en el minibar de un hotel.",
    "gen189": "Nombra algo que encontrarias dentro de un casillero escolar.",
    "gen190": "Nombra algo que seria un mal regalo de cumpleanos.",
    "gen191": "Nombra un animal que sorprende que se pueda tener como mascota.",
    "gen192": "Nombra algo que un maestro dice todos los dias.",
    "gen193": "Nombra algo que hace que un vecindario se sienta seguro.",
    "gen194": "Nombra algo que verias en un carnaval.",
    "gen195": "Nombra una tarea del hogar que los ninos tratan de evitar.",
    "gen196": "Nombra algo que la gente hace justo despues de hacer ejercicio.",
    "gen197": "Nombra algo que es amarillo.",
    "gen198": "Nombra algo que la gente desearia haber empezado a hacer antes.",
    "gen199": "Nombra algo que la gente siempre olvida cuando va de campamento.",
    "gen200": "Nombra algo que la gente hace a medianoche en Ano Nuevo.",
}
