# Spanish question translations for gen201-gen300 (ASCII-safe)
ES_QUESTIONS_NEW2 = {
    "gen201": "Nombra una celebridad que todos reconocen solo por su primer nombre.",
    "gen202": "Nombra algo que la gente hace cuando un viaje en ascensor es incomodo.",
    "gen203": "Nombra un alimento sobre el que la gente discute si es fruta o verdura.",
    "gen204": "Nombra algo que siempre esta en el fondo de tu refrigerador.",
    "gen205": "Nombra una habilidad que es inutil pero impresionante.",
    "gen206": "Nombra algo que los abuelos siempre dicen.",
    "gen207": "Nombra una palabra que la gente comunmente usa incorrectamente.",
    "gen208": "Nombra algo que la gente finge disfrutar pero secretamente odia.",
    "gen209": "Nombra un animal que te aterrorizaria encontrar en tu casa.",
    "gen210": "Nombra algo que la gente siempre pierde.",
    "gen211": "Nombra una pelicula que todos han visto pero nadie admite que les encanta.",
    "gen212": "Nombra algo que encontrarias en el piso del cuarto de un adolescente desordenado.",
    "gen213": "Nombra algo que a la gente le da verguenza comprar en la tienda.",
    "gen214": "Nombra una profesion en la que esperarias que la persona este en gran forma.",
    "gen215": "Nombra una cancion de la que todos saben la letra.",
    "gen216": "Nombra un pais que la gente suena con visitar algun dia.",
    "gen217": "Nombra algo que la gente hace para procrastinar.",
    "gen218": "Nombra un olor que instantaneamente trae recuerdos de la infancia.",
    "gen219": "Nombra algo que toma una eternidad en la oficina de vehiculos.",
    "gen220": "Nombra un deporte que parece facil pero en realidad es muy dificil.",
    "gen221": "Nombra algo sobre lo que la gente miente en su perfil de citas.",
    "gen222": "Nombra algo que un perro diria si pudiera hablar.",
    "gen223": "Nombra una razon por la que la gente se reporta enferma sin estarlo.",
    "gen224": "Nombra una comida que es imposible de comer limpiamente.",
    "gen225": "Nombra algo que siempre parece romperse en el peor momento.",
    "gen226": "Nombra un trabajo que los ninos dicen que quieren cuando crezcan.",
    "gen227": "Nombra un dia festivo para el que la gente empieza a prepararse demasiado temprano.",
    "gen228": "Nombra algo que es mejor hecho en casa que comprado en tienda.",
    "gen229": "Nombra algo que la gente acumula aunque no lo necesite.",
    "gen230": "Nombra un sonido que es instantaneamente reconocible.",
    "gen231": "Nombra un sitio web que todos han visitado al menos una vez.",
    "gen232": "Nombra una excusa que la gente da por llegar tarde.",
    "gen233": "Nombra un lugar donde te ves obligado a hacer conversacion incomoda.",
    "gen234": "Nombra algo por lo que la gente pelea en Accion de Gracias.",
    "gen235": "Nombra una razon por la que la gente evita ir al doctor.",
    "gen236": "Nombra una verdura que los ninos se niegan a comer.",
    "gen237": "Nombra algo que es socialmente aceptable para ninos pero raro para adultos.",
    "gen238": "Nombra algo que encontrarias en un cajon de cosas varias.",
    "gen239": "Nombra una aplicacion a la que la gente es adicta.",
    "gen240": "Nombra algo que la gente dice que hara en Ano Nuevo pero nunca hace.",
    "gen241": "Nombra algo que hace divertido un viaje por carretera.",
    "gen242": "Nombra algo que es mucho mas caro de lo que deberia ser.",
    "gen243": "Nombra un animal que la gente tiene como mascota pero probablemente no deberia.",
    "gen244": "Nombra algo que finges entender pero realmente no entiendes.",
    "gen245": "Nombra algo que encuentras en cada fiesta de cumpleanos.",
    "gen246": "Nombra un tipo de clima que arruina los planes al aire libre.",
    "gen247": "Nombra algo que la gente tiene miedo de pedirle a su jefe.",
    "gen248": "Nombra un sabor de helado que a casi todos les gusta.",
    "gen249": "Nombra algo que la gente hace justo antes de ir a dormir.",
    "gen250": "Nombra un juego de mesa que causa mas discusiones familiares.",
    "gen251": "Nombra algo de lo que la gente presume en redes sociales.",
    "gen252": "Nombra un sonido que instantaneamente te lleva a la infancia.",
    "gen253": "Nombra un trabajo que las peliculas hacen ver mucho mas genial de lo que es.",
    "gen254": "Nombra algo que nunca eres demasiado viejo para disfrutar.",
    "gen255": "Nombra una combinacion de comida que suena rara pero en realidad es buena.",
    "gen256": "Nombra algo que la gente hace cuando esta nerviosa.",
    "gen257": "Nombra un articulo por el que la gente pelea en una venta.",
    "gen258": "Que es algo que la gente siempre pierde?",
    "gen259": "Nombra una razon por la que la gente se reporta enferma sin estar enferma.",
    "gen260": "Nombra algo que encontrarias en la casa de cada abuela.",
    "gen261": "Nombra una celebridad de la que todos pueden hacer una imitacion.",
    "gen262": "Nombra algo que la gente hace en su telefono mientras finge escuchar.",
    "gen263": "Nombra un animal que seria terrible como mascota.",
    "gen264": "Nombra algo que la gente siempre dice que empezara el lunes.",
    "gen265": "Nombra un lugar donde la gente siempre susurra.",
    "gen266": "Nombra una comida que la gente come demasiado en una fiesta.",
    "gen267": "Nombra algo de lo que la gente finge saber pero en realidad no sabe.",
    "gen268": "Nombra algo que siempre se queda atorado en tus dientes.",
    "gen269": "Cual pelicula han visto todos al menos una vez?",
    "gen270": "Nombra un lugar donde odiarias tener una llanta ponchada.",
    "gen271": "Que huele bien pero sabe terrible?",
    "gen272": "Nombra algo que la gente colecciona y otros piensan que es raro.",
    "gen273": "Nombra algo que siempre olvidas empacar para un viaje.",
    "gen274": "Nombra una cancion de la que todos saben la letra.",
    "gen275": "Que es algo que es mas dificil de lo que parece?",
    "gen276": "Nombra una excusa que la gente da por llegar tarde.",
    "gen277": "Que siempre se esconde en un cajon de cosas varias?",
    "gen278": "Nombra un deporte que parece facil pero en realidad es agotador.",
    "gen279": "Nombra algo por lo que secretamente juzgas a otras personas.",
    "gen280": "Nombra algo que la gente hace para parecer ocupada en el trabajo.",
    "gen281": "Nombra un sonido de animal que todos pueden imitar.",
    "gen282": "Que toma mucho mas tiempo de lo que deberia?",
    "gen283": "Cual dia festivo la gente secretamente teme?",
    "gen284": "Que les da verguenza a las personas pedir indicaciones para llegar a?",
    "gen285": "Que siempre parece romperse en el peor momento?",
    "gen286": "Nombra una palabra que la gente comunmente escribe mal.",
    "gen287": "Nombra algo que hace un viaje por carretera mas divertido.",
    "gen288": "Que encontrarias en el cuarto de un adolescente?",
    "gen289": "Nombra una mentira que los padres les dicen a sus hijos.",
    "gen290": "Nombra algo que es mejor hecho en casa que comprado en tienda.",
    "gen291": "Que acumula la gente aunque no lo necesite?",
    "gen292": "Nombra algo que odiarias descubrir en tu cuarto de hotel.",
    "gen293": "Nombra una habilidad que impresiona a la gente en una fiesta.",
    "gen294": "Que hace la gente en la ducha ademas de banarse?",
    "gen295": "Nombra un juego que ha arruinado amistades.",
    "gen296": "Que finges disfrutar como adulto?",
    "gen297": "Nombra una ocupacion con un uniforme genial.",
    "gen298": "Nombra algo que siempre sabe mejor en un restaurante.",
    "gen299": "Nombra algo que la gente desea haber aprendido en la escuela.",
    "gen300": "Que instantaneamente mejora un mal dia?",
}
